using System.Net;
using System.Text;

using GitLab.Client.Abstractions.Exceptions;
using GitLab.Client.Endpoints;
using GitLab.Client.Infrastructure.Http;
using GitLab.Client.Models;
using GitLab.Client.Models.Requests;
using GitLab.Client.Tests.TestSupport;

namespace GitLab.Client.Tests.Endpoints;

public sealed class ErrorTrackingEndpointTests
{
    private const string ClientKeyJson = """
                                         {
                                           "id": 1,
                                           "active": true,
                                           "public_key": "glet_aa77551d849c083f76d0bc545ed053a3",
                                           "sentry_dsn": "https://glet_aa77551d849c083f76d0bc545ed053a3@example.com/errortracking/api/v1/projects/5"
                                         }
                                         """;

    private const string SettingsJson = """
                                        {
                                          "active": true,
                                          "project_name": "sample sentry project",
                                          "sentry_external_url": "https://sentry.io/myawesomeproject/project",
                                          "api_url": "https://sentry.io/api/0/projects/myawesomeproject/project",
                                          "integrated": false
                                        }
                                        """;

    [Fact]
    public async Task ListClientKeysAsync_EncodesNamespacedProjectPath_AndDeserializesTheDsn()
    {
        string json = $"[{ClientKeyJson}]";

        using StubHttpMessageHandler handler = new(_ => new HttpResponseMessage(HttpStatusCode.OK)
        {
            Content = new StringContent(json, Encoding.UTF8, "application/json")
        });

        using HttpClient httpClient = new(handler) { BaseAddress = new Uri("https://gitlab.example/api/v4/") };
        GitLabApiConnection connection = new(httpClient);
        ErrorTrackingClient repository = new(connection);

        List<GitLabErrorTrackingClientKey> keys = new();
        await foreach (GitLabErrorTrackingClientKey item in repository.ListClientKeysAsync("gitlab-org/gitlab",
                           TestContext.Current.CancellationToken))
        {
            keys.Add(item);
        }

        Assert.Equal(HttpMethod.Get, handler.LastRequest?.Method);
        Assert.Equal(
            "https://gitlab.example/api/v4/projects/gitlab-org%2Fgitlab/error_tracking/client_keys",
            handler.LastRequest?.RequestUri?.AbsoluteUri);

        GitLabErrorTrackingClientKey key = Assert.Single(keys);
        Assert.Equal(1, key.Id);
        Assert.True(key.Active);
        Assert.Equal("glet_aa77551d849c083f76d0bc545ed053a3", key.PublicKey);
        Assert.Equal("https://glet_aa77551d849c083f76d0bc545ed053a3@example.com/errortracking/api/v1/projects/5",
            key.SentryDsn?.ToString());
    }

    [Fact]
    public async Task CreateClientKeyAsync_PostsWithNoBody_AndReturnsTheGeneratedKey()
    {
        using StubHttpMessageHandler handler = new(_ => new HttpResponseMessage(HttpStatusCode.Created)
        {
            Content = new StringContent(ClientKeyJson, Encoding.UTF8, "application/json")
        });

        using HttpClient httpClient = new(handler) { BaseAddress = new Uri("https://gitlab.example/api/v4/") };
        GitLabApiConnection connection = new(httpClient);
        ErrorTrackingClient repository = new(connection);

        GitLabErrorTrackingClientKey key =
            await repository.CreateClientKeyAsync(42, TestContext.Current.CancellationToken);

        Assert.Equal(HttpMethod.Post, handler.LastRequest?.Method);
        Assert.Equal("https://gitlab.example/api/v4/projects/42/error_tracking/client_keys",
            handler.LastRequest?.RequestUri?.AbsoluteUri);

        // The public key is generated by GitLab; the endpoint declares no request body at all.
        Assert.Null(handler.LastRequest?.Content);

        Assert.Equal("glet_aa77551d849c083f76d0bc545ed053a3", key.PublicKey);
    }

    [Fact]
    public async Task DeleteClientKeyAsync_BuildsRouteWithKeyId_AndReturnsTheDeletedKey()
    {
        using StubHttpMessageHandler handler = new(_ => new HttpResponseMessage(HttpStatusCode.OK)
        {
            Content = new StringContent(ClientKeyJson, Encoding.UTF8, "application/json")
        });

        using HttpClient httpClient = new(handler) { BaseAddress = new Uri("https://gitlab.example/api/v4/") };
        GitLabApiConnection connection = new(httpClient);
        ErrorTrackingClient repository = new(connection);

        GitLabErrorTrackingClientKey key =
            await repository.DeleteClientKeyAsync(42, 1, TestContext.Current.CancellationToken);

        Assert.Equal(HttpMethod.Delete, handler.LastRequest?.Method);
        Assert.Equal("https://gitlab.example/api/v4/projects/42/error_tracking/client_keys/1",
            handler.LastRequest?.RequestUri?.AbsoluteUri);
        Assert.Equal(1, key.Id);
    }

    [Fact]
    public async Task GetSettingsAsync_BuildsSettingsRoute_AndDeserializesUrls()
    {
        using StubHttpMessageHandler handler = new(_ => new HttpResponseMessage(HttpStatusCode.OK)
        {
            Content = new StringContent(SettingsJson, Encoding.UTF8, "application/json")
        });

        using HttpClient httpClient = new(handler) { BaseAddress = new Uri("https://gitlab.example/api/v4/") };
        GitLabApiConnection connection = new(httpClient);
        ErrorTrackingClient repository = new(connection);

        GitLabErrorTrackingSettings settings =
            await repository.GetSettingsAsync(42, TestContext.Current.CancellationToken);

        Assert.Equal(HttpMethod.Get, handler.LastRequest?.Method);
        Assert.Equal("https://gitlab.example/api/v4/projects/42/error_tracking/settings",
            handler.LastRequest?.RequestUri?.AbsoluteUri);
        Assert.True(settings.Active);
        Assert.False(settings.Integrated);
        Assert.Equal("sample sentry project", settings.ProjectName);
        Assert.Equal("https://sentry.io/myawesomeproject/project", settings.SentryExternalUrl?.ToString());
        Assert.Equal("https://sentry.io/api/0/projects/myawesomeproject/project", settings.ApiUrl?.ToString());
    }

    [Fact]
    public async Task UpdateSettingsAsync_SendsPatch_WithOnlyTheSetMembers()
    {
        string? sentBody = null;
        using StubHttpMessageHandler handler = new(request =>
        {
            sentBody = request.Content?.ReadAsStringAsync().GetAwaiter().GetResult();
            return new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = new StringContent(SettingsJson, Encoding.UTF8, "application/json")
            };
        });

        using HttpClient httpClient = new(handler) { BaseAddress = new Uri("https://gitlab.example/api/v4/") };
        GitLabApiConnection connection = new(httpClient);
        ErrorTrackingClient repository = new(connection);

        UpdateErrorTrackingSettingsRequest request = new() { Active = true };

        GitLabErrorTrackingSettings settings =
            await repository.UpdateSettingsAsync(42, request, TestContext.Current.CancellationToken);

        Assert.Equal(HttpMethod.Patch, handler.LastRequest?.Method);
        Assert.Equal("https://gitlab.example/api/v4/projects/42/error_tracking/settings",
            handler.LastRequest?.RequestUri?.AbsoluteUri);
        Assert.Equal("""{"active":true}""", sentBody);
        Assert.True(settings.Active);
    }

    [Fact]
    public async Task CreateSettingsAsync_SendsPut_WithBothRequiredMembers()
    {
        string? sentBody = null;
        using StubHttpMessageHandler handler = new(request =>
        {
            sentBody = request.Content?.ReadAsStringAsync().GetAwaiter().GetResult();
            return new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = new StringContent(SettingsJson, Encoding.UTF8, "application/json")
            };
        });

        using HttpClient httpClient = new(handler) { BaseAddress = new Uri("https://gitlab.example/api/v4/") };
        GitLabApiConnection connection = new(httpClient);
        ErrorTrackingClient repository = new(connection);

        CreateErrorTrackingSettingsRequest request = new() { Active = true, Integrated = false };

        GitLabErrorTrackingSettings settings =
            await repository.CreateSettingsAsync(42, request, TestContext.Current.CancellationToken);

        Assert.Equal(HttpMethod.Put, handler.LastRequest?.Method);
        Assert.Equal("https://gitlab.example/api/v4/projects/42/error_tracking/settings",
            handler.LastRequest?.RequestUri?.AbsoluteUri);
        Assert.Equal("""{"active":true,"integrated":false}""", sentBody);
        Assert.False(settings.Integrated);
    }

    [Fact]
    public async Task GetSettingsAsync_OnMissingSettings_ThrowsGitLabNotFoundException()
    {
        const string Json = """{ "message": "404 Not found" }""";

        using StubHttpMessageHandler handler = new(_ => new HttpResponseMessage(HttpStatusCode.NotFound)
        {
            Content = new StringContent(Json, Encoding.UTF8, "application/json")
        });

        using HttpClient httpClient = new(handler) { BaseAddress = new Uri("https://gitlab.example/api/v4/") };
        GitLabApiConnection connection = new(httpClient);
        ErrorTrackingClient repository = new(connection);

        GitLabApiException exception = await Assert.ThrowsAsync<GitLabNotFoundException>(() =>
            repository.GetSettingsAsync(42, TestContext.Current.CancellationToken));

        Assert.Equal(HttpStatusCode.NotFound, exception.StatusCode);
    }
}