using System.Collections.Immutable;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace GitLab.Client.SourceGenerators;

/// <summary>
///     Generates the Service and Controller delegation layers for a resource, from a Repository
///     interface marked <c>[GenerateClientLayers(typeof(IXxxService), typeof(IXxxClient))]</c>.
///     Both generated classes are pure 1:1 forwarders (Controller -> Service -> Repository) with
///     no hand-written logic, so every GitLab resource gets the same Controllers/Services/Repositories
///     layering the project's architecture calls for, without hand-authoring two boilerplate classes
///     per resource. This is compile-time-only: nothing here runs, or is reachable, at the consumer's
///     runtime, so it has no bearing on Native AOT/trimming.
///     <para>
///         Nothing symbolic crosses from the transform stage into the pipeline model - see
///         <see cref="ClientLayersModel" />. An <c>ISymbol</c> in the model would give it reference
///         equality (so the driver would re-render every resource on every keystroke) and would root a
///         whole <see cref="Compilation" /> in the driver cache for the life of an IDE session.
///     </para>
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class GenerateClientLayersGenerator : IIncrementalGenerator
{
    private const string GeneratorName = "GitLab.Client.SourceGenerators";

    /// <summary>
    ///     Hand-maintained on purpose. This string is baked into every generated file, so deriving it from
    ///     the running assembly's version would churn the whole of <c>obj/Generated</c> on every rebuild
    ///     of the generator.
    /// </summary>
    private const string GeneratorVersion = "1.0.0";

    private const string DependencyParameterName = "dependency";

    private const string AttributeSource = """
                                           // <auto-generated/>
                                           #nullable enable

                                           namespace GitLab.Client.SourceGenerators
                                           {
                                               /// <summary>
                                               /// Marks a resource Repository interface for compile-time generation of its Service and
                                               /// Controller delegation layers, its dependency-injection registrations, and its property
                                               /// on the root IGitLabClient. Apply to an internal repository interface:
                                               /// <c>[GenerateClientLayers(typeof(IProjectsService), typeof(IProjectsClient))]</c>.
                                               /// </summary>
                                               [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                                               [global::System.AttributeUsage(global::System.AttributeTargets.Interface, AllowMultiple = false, Inherited = false)]
                                               internal sealed class GenerateClientLayersAttribute : global::System.Attribute
                                               {
                                                   public GenerateClientLayersAttribute(global::System.Type serviceInterface, global::System.Type clientInterface)
                                                   {
                                                       ServiceInterface = serviceInterface;
                                                       ClientInterface = clientInterface;
                                                   }

                                                   public global::System.Type ServiceInterface { get; }

                                                   public global::System.Type ClientInterface { get; }

                                                   /// <summary>
                                                   /// Overrides the namespace the generated Service class is emitted into. Defaults to the
                                                   /// repository interface's namespace with its "Repositories" segment replaced by "Services".
                                                   /// </summary>
                                                   public string? ServiceNamespace { get; set; }

                                                   /// <summary>
                                                   /// Overrides the namespace the generated Controller class is emitted into. Defaults to the
                                                   /// repository interface's namespace with its "Repositories" segment replaced by "Controllers".
                                                   /// </summary>
                                                   public string? ControllerNamespace { get; set; }

                                                   /// <summary>
                                                   /// Emit dependency-injection registrations for this resource. Set false to register it by
                                                   /// hand in AddGitLabClient - for a custom lifetime, or a decorator around the controller.
                                                   /// </summary>
                                                   public bool Register { get; set; } = true;

                                                   /// <summary>
                                                   /// Expose this resource as a property on IGitLabClient. Set false to keep a deprecated or
                                                   /// niche area off the curated root surface while leaving its client independently injectable.
                                                   /// </summary>
                                                   public bool ExposeOnRootClient { get; set; } = true;

                                                   /// <summary>
                                                   /// Overrides the IGitLabClient property name, which defaults to the resource name derived
                                                   /// from the repository interface (IProjectsRepository -&gt; Projects).
                                                   /// </summary>
                                                   public string? RootPropertyName { get; set; }
                                               }
                                           }
                                           """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            // Defines Microsoft.CodeAnalysis.EmbeddedAttribute itself, so the marker attribute below
            // can be marked embedded: compiled straight into GitLab.Client with no shared/runtime
            // dependency on this generator project, and safe even if this generator is ever
            // referenced by more than one project in the same solution.
            //
            // This generator is the SOLE owner of the marker attribute. GitLabClientWiringGenerator
            // lives in the same assembly and only matches on it by metadata name; if it ever emitted
            // the attribute too, post-init sources from both generators would land in one compilation
            // and define the type twice (CS0101).
            ctx.AddEmbeddedAttributeDefinition();
            ctx.AddSource("GenerateClientLayersAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8));
        });

        IncrementalValuesProvider<ClientLayersModel> models = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                ClientLayerNaming.AttributeFullName,
                static (node, _) => node is InterfaceDeclarationSyntax,
                static (ctx, token) => TryCreateModel(ctx, token))
            .Where(static model => model.HasValue)
            .Select(static (model, _) => model!.Value)
            .WithTrackingName(TrackingNames.LayerModels);

        // A separate diagnostic-only node: collision detection needs every resource at once, and doing
        // it here keeps the per-resource source outputs independently cacheable. The .Collect() result
        // is an ImmutableArray (reference equality), so it is immediately projected into a value-
        // equatable EquatableArray to stop the output node firing on every run.
        IncrementalValueProvider<EquatableArray<DiagnosticInfo>> collisions = models
            .Where(static model => !model.HasError)
            .Select(static (model, _) => new LayerKey(
                model.Service.NamespaceName + "." + model.Service.ClassName,
                model.Controller.NamespaceName + "." + model.Controller.ClassName,
                model.RepositoryInterface,
                model.AttributeLocation))
            .Collect()
            .Select(static (keys, _) => FindCollisions(keys))
            .WithTrackingName(TrackingNames.LayerCollisions);

        context.RegisterSourceOutput(collisions, static (spc, diagnostics) => Report(spc, diagnostics));
        context.RegisterSourceOutput(models, static (spc, model) => Emit(spc, model));
    }

    private static void Report(SourceProductionContext context, EquatableArray<DiagnosticInfo> diagnostics)
    {
        foreach (DiagnosticInfo diagnostic in diagnostics)
        {
            context.ReportDiagnostic(diagnostic.ToDiagnostic());
        }
    }

    private static void Emit(SourceProductionContext context, ClientLayersModel model)
    {
        Report(context, model.Diagnostics);

        if (model.HasError)
        {
            return;
        }

        context.AddSource(model.HintNamePrefix + ".Service.g.cs",
            SourceText.From(RenderLayer(model.Service), Encoding.UTF8));
        context.AddSource(model.HintNamePrefix + ".Controller.g.cs",
            SourceText.From(RenderLayer(model.Controller), Encoding.UTF8));
    }

    private static EquatableArray<DiagnosticInfo> FindCollisions(ImmutableArray<LayerKey> keys)
    {
        List<DiagnosticInfo> diagnostics = new();

        foreach (IGrouping<string, LayerKey> group in keys.GroupBy(
                     static key => key.QualifiedServiceName + "|" + key.QualifiedControllerName,
                     StringComparer.Ordinal))
        {
            List<LayerKey> colliding = group.ToList();

            if (colliding.Count <= 1)
            {
                continue;
            }

            string owners = string.Join(", ", colliding.Select(static key => key.RepositoryInterface).OrderBy(
                static name => name, StringComparer.Ordinal));

            foreach (LayerKey key in colliding)
            {
                diagnostics.Add(DiagnosticInfo.Create(
                    Descriptors.DuplicateGeneratedLayer,
                    key.Location,
                    colliding[0].QualifiedServiceName,
                    owners));
            }
        }

        return EquatableArray<DiagnosticInfo>.From(diagnostics);
    }

    private static ClientLayersModel? TryCreateModel(GeneratorAttributeSyntaxContext ctx,
        CancellationToken cancellationToken)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol repositoryInterface)
        {
            return null;
        }

        AttributeData? attribute = ctx.Attributes.FirstOrDefault();

        // A different arity only happens when the attribute itself failed to bind, which the compiler
        // has already reported; adding a diagnostic of our own on top of that would be noise.
        if (attribute is null || attribute.ConstructorArguments.Length != 2)
        {
            return null;
        }

        LocationInfo? location = LocationInfo.CreateFrom(GetTargetLocation(ctx.TargetNode));
        List<DiagnosticInfo> diagnostics = new();

        INamedTypeSymbol? serviceInterface =
            ResolveInterfaceArgument(attribute, 0, repositoryInterface, location, diagnostics);
        INamedTypeSymbol? clientInterface =
            ResolveInterfaceArgument(attribute, 1, repositoryInterface, location, diagnostics);

        if (serviceInterface is null || clientInterface is null)
        {
            return CreateErrorModel(repositoryInterface, location, diagnostics);
        }

        if (repositoryInterface.IsGenericType ||
            repositoryInterface.ContainingType is not null ||
            repositoryInterface.ContainingNamespace.IsGlobalNamespace)
        {
            diagnostics.Add(DiagnosticInfo.Create(Descriptors.UnsupportedRepositoryShape, location,
                repositoryInterface.ToDisplayString()));
            return CreateErrorModel(repositoryInterface, location, diagnostics);
        }

        string resourceName = ClientLayerNaming.GetResourceName(repositoryInterface.Name);

        if (!FollowsNamingConvention(repositoryInterface.Name) || resourceName.Length == 0)
        {
            diagnostics.Add(DiagnosticInfo.Create(Descriptors.RepositoryNamingConvention, location,
                repositoryInterface.ToDisplayString(), resourceName));
        }

        string repositoryNamespace = repositoryInterface.ContainingNamespace.ToDisplayString();
        string serviceNamespace = NamedArgument(attribute, "ServiceNamespace") as string ??
                                  ClientLayerNaming.DeriveLayerNamespace(repositoryNamespace,
                                      ClientLayerNaming.ServicesLayerSegment);
        string controllerNamespace = NamedArgument(attribute, "ControllerNamespace") as string ??
                                     ClientLayerNaming.DeriveLayerNamespace(repositoryNamespace,
                                         ClientLayerNaming.ControllersLayerSegment);

        LayerModel service = CreateLayerModel(
            resourceName + ClientLayerNaming.ServiceSuffix, serviceNamespace,
            serviceInterface, repositoryInterface, diagnostics, location, cancellationToken);
        LayerModel controller = CreateLayerModel(
            resourceName + ClientLayerNaming.ControllerSuffix, controllerNamespace,
            clientInterface, serviceInterface, diagnostics, location, cancellationToken);

        return new ClientLayersModel(
            resourceName,
            repositoryInterface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            service,
            controller,
            repositoryNamespace + "." + repositoryInterface.Name,
            location,
            EquatableArray<DiagnosticInfo>.From(diagnostics),
            HasError(diagnostics));
    }

    private static LayerModel CreateLayerModel(
        string className,
        string namespaceName,
        INamedTypeSymbol implementedInterface,
        INamedTypeSymbol dependencyInterface,
        List<DiagnosticInfo> diagnostics,
        LocationInfo? location,
        CancellationToken cancellationToken)
    {
        List<IMethodSymbol> methods = new();
        List<IPropertySymbol> properties = new();

        ClientLayerSymbolReader.CollectMembers(implementedInterface, methods, properties, diagnostics, location,
            cancellationToken);
        ClientLayerSymbolReader.VerifyForwardable(implementedInterface, dependencyInterface, methods, properties,
            diagnostics, location, cancellationToken);

        if (methods.Count == 0 && properties.Count == 0)
        {
            diagnostics.Add(DiagnosticInfo.Create(Descriptors.EmptyGeneratedLayer, location,
                implementedInterface.ToDisplayString(), className));
        }

        List<MethodModel> methodModels = new();

        foreach (IMethodSymbol method in methods)
        {
            methodModels.Add(ClientLayerSymbolReader.CreateMethodModel(method, diagnostics, location));
        }

        List<PropertyModel> propertyModels = new();

        foreach (IPropertySymbol property in properties)
        {
            propertyModels.Add(ClientLayerSymbolReader.CreatePropertyModel(property));
        }

        return new LayerModel(
            className,
            namespaceName,
            ClientLayerSymbolReader.Fqn(implementedInterface),
            ClientLayerSymbolReader.Fqn(dependencyInterface),
            EquatableArray<MethodModel>.From(methodModels),
            EquatableArray<PropertyModel>.From(propertyModels));
    }

    private static ClientLayersModel CreateErrorModel(INamedTypeSymbol repositoryInterface, LocationInfo? location,
        List<DiagnosticInfo> diagnostics)
    {
        LayerModel empty = new(string.Empty, string.Empty, string.Empty, string.Empty,
            EquatableArray<MethodModel>.Empty, EquatableArray<PropertyModel>.Empty);

        return new ClientLayersModel(
            string.Empty,
            repositoryInterface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            empty,
            empty,
            string.Empty,
            location,
            EquatableArray<DiagnosticInfo>.From(diagnostics),
            true);
    }

    private static bool HasError(List<DiagnosticInfo> diagnostics)
    {
        foreach (DiagnosticInfo diagnostic in diagnostics)
        {
            if (diagnostic.Descriptor.DefaultSeverity == DiagnosticSeverity.Error)
            {
                return true;
            }
        }

        return false;
    }

    private static bool FollowsNamingConvention(string repositoryInterfaceName)
    {
        return repositoryInterfaceName.Length > 1 &&
               repositoryInterfaceName[0] == 'I' &&
               char.IsUpper(repositoryInterfaceName[1]) &&
               repositoryInterfaceName.EndsWith(ClientLayerNaming.RepositorySuffix, StringComparison.Ordinal);
    }

    private static object? NamedArgument(AttributeData attribute, string name)
    {
        foreach (KeyValuePair<string, TypedConstant> argument in attribute.NamedArguments)
        {
            if (string.Equals(argument.Key, name, StringComparison.Ordinal))
            {
                return argument.Value.Value;
            }
        }

        return null;
    }

    /// <summary>
    ///     <see cref="IErrorTypeSymbol" /> derives from <see cref="INamedTypeSymbol" />, so a
    ///     <c>typeof(ITypoService)</c> naming a type that does not exist would otherwise pass a plain type
    ///     test and make the generator emit a class deriving from an unresolved name. The compiler has
    ///     already reported CS0246 there, so that case bails out silently; only a resolved type that is
    ///     genuinely not an interface earns GLC0001.
    /// </summary>
    private static INamedTypeSymbol? ResolveInterfaceArgument(AttributeData attribute, int index,
        INamedTypeSymbol repositoryInterface, LocationInfo? location, List<DiagnosticInfo> diagnostics)
    {
        if (attribute.ConstructorArguments[index].Value is not INamedTypeSymbol candidate ||
            candidate.TypeKind == TypeKind.Error)
        {
            return null;
        }

        if (candidate.TypeKind != TypeKind.Interface)
        {
            diagnostics.Add(DiagnosticInfo.Create(Descriptors.ArgumentMustBeInterface, location,
                candidate.ToDisplayString(), repositoryInterface.ToDisplayString()));
            return null;
        }

        return candidate;
    }

    private static Location GetTargetLocation(SyntaxNode node)
    {
        return node is InterfaceDeclarationSyntax declaration
            ? declaration.Identifier.GetLocation()
            : node.GetLocation();
    }

    private static string RenderLayer(LayerModel model)
    {
        StringBuilder builder = new();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        // The auto-generated header and the .g.cs suffix keep analyzers off this file, but they do not
        // suppress core compiler warnings, and TreatWarningsAsErrors makes those a build break on a file
        // nobody can edit. CS9113: the dependency parameter is unread when the interface declares no
        // members (GLC0007 says so on the interface itself). CS0612/CS0618: a resource area may
        // legitimately be [Obsolete] under the deprecation policy in CLAUDE.md.
        builder.AppendLine("#pragma warning disable CS9113");
        builder.AppendLine("#pragma warning disable CS0612, CS0618");
        builder.AppendLine();
        builder.Append("namespace ").AppendLine(model.NamespaceName);
        builder.AppendLine("{");
        builder.Append("    [global::System.CodeDom.Compiler.GeneratedCode(\"").Append(GeneratorName)
            .Append("\", \"").Append(GeneratorVersion).AppendLine("\")]");
        builder.AppendLine("    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        builder.AppendLine("    [global::System.Diagnostics.DebuggerNonUserCode]");
        builder.Append("    internal sealed class ").Append(model.ClassName)
            .Append('(').Append(model.DependencyInterface).Append(' ').Append(DependencyParameterName).Append(')')
            .Append(" : ").AppendLine(model.ImplementedInterface);
        builder.AppendLine("    {");

        bool first = true;

        foreach (PropertyModel property in model.Properties)
        {
            AppendSeparator(builder, ref first);
            AppendProperty(builder, property);
        }

        foreach (MethodModel method in model.Methods)
        {
            AppendSeparator(builder, ref first);
            AppendMethod(builder, method);
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("#pragma warning restore CS0612, CS0618");
        builder.AppendLine("#pragma warning restore CS9113");
        return builder.ToString();
    }

    private static void AppendSeparator(StringBuilder builder, ref bool first)
    {
        if (!first)
        {
            builder.AppendLine();
        }

        first = false;
    }

    private static void AppendProperty(StringBuilder builder, PropertyModel property)
    {
        builder.Append("        public ").Append(property.Type).Append(' ').Append(property.Name);

        if (property.HasGetter && !property.HasSetter)
        {
            builder.Append(" => ").Append(DependencyParameterName).Append('.').Append(property.Name).AppendLine(";");
            return;
        }

        builder.Append(" { ");

        if (property.HasGetter)
        {
            builder.Append("get => ").Append(DependencyParameterName).Append('.').Append(property.Name).Append("; ");
        }

        if (property.HasSetter)
        {
            builder.Append("set => ").Append(DependencyParameterName).Append('.').Append(property.Name)
                .Append(" = value; ");
        }

        builder.AppendLine("}");
    }

    private static void AppendMethod(StringBuilder builder, MethodModel method)
    {
        builder.Append("        ").Append(method.ReturnAttributes).Append("public ").Append(method.ReturnType)
            .Append(' ').Append(method.Name).Append(method.TypeParameterList).Append('(');

        for (int index = 0; index < method.Parameters.Length; index++)
        {
            if (index > 0)
            {
                builder.Append(", ");
            }

            ParameterModel parameter = method.Parameters[index];
            builder.Append(parameter.Attributes).Append(parameter.Modifiers).Append(parameter.Type).Append(' ')
                .Append(parameter.Name);

            if (parameter.DefaultValue is not null)
            {
                builder.Append(" = ").Append(parameter.DefaultValue);
            }
        }

        builder.Append(')');

        foreach (string clause in method.ConstraintClauses)
        {
            builder.AppendLine().Append("            ").Append(clause);
        }

        builder.Append(" => ").Append(DependencyParameterName).Append('.').Append(method.Name)
            .Append(method.TypeParameterList).Append('(');

        for (int index = 0; index < method.Parameters.Length; index++)
        {
            if (index > 0)
            {
                builder.Append(", ");
            }

            ParameterModel parameter = method.Parameters[index];
            builder.Append(parameter.ArgumentPrefix).Append(parameter.Name);
        }

        builder.AppendLine(");");
    }
}