using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace GitLab.Client.SourceGenerators;

/// <summary>
///     Generates the query-string projection for every options type marked <c>[GitLabQuery]</c>, and
///     the wire-value helper for every string-serialised GitLab enum.
///     <para>
///         GitLab runs Grape, which silently ignores an unknown query parameter and answers 200 with
///         unfiltered results, so a misspelled wire name is an invisible production bug. Deriving the
///         name from the property at compile time removes the place that typo can live: the default is
///         a snake_case of the C# property name, and the ~6% of GitLab's parameter names that do not
///         fall out of that rule (<c>not[labels]</c>, <c>filter[environment_scope]</c>, ...) carry an
///         explicit <c>[QueryParameter("...")]</c>. A property whose type has no mapping is a build
///         error naming the property, never a silently dropped parameter.
///     </para>
///     <para>
///         Nothing here runs at the consumer's runtime - the emitted code is plain
///         <c>builder.Query("per_page", options.PerPage);</c> statements - so this has no bearing on
///         Native AOT or trimming.
///     </para>
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class GitLabQueryGenerator : IIncrementalGenerator
{
    private const string QueryAttributeFullName = "GitLab.Client.SourceGenerators.GitLabQueryAttribute";
    private const string ParameterAttributeFullName = "GitLab.Client.SourceGenerators.QueryParameterAttribute";
    private const string IgnoreAttributeFullName = "GitLab.Client.SourceGenerators.QueryIgnoreAttribute";
    private const string JsonConverterAttributeFullName = "System.Text.Json.Serialization.JsonConverterAttribute";

    private const string EnumMemberNameAttributeFullName =
        "System.Text.Json.Serialization.JsonStringEnumMemberNameAttribute";

    private const string StringEnumConverterMetadataName = "JsonStringEnumConverter`1";
    private const string JsonSerializationNamespace = "System.Text.Json.Serialization";
    private const string RoutingNamespace = "GitLab.Client.Infrastructure.Routing";
    private const string BuilderTypeName = "global::GitLab.Client.Infrastructure.Routing.GitLabRouteBuilder";
    private const string ReadOnlyListDefinition = "System.Collections.Generic.IReadOnlyList<T>";
    private const string DateTimeOffsetTypeName = "System.DateTimeOffset";
    private const string DateOnlyTypeName = "System.DateOnly";
    private const string Category = "GitLabQuery";

    private const string AttributeSource = """
                                           // <auto-generated/>
                                           #nullable enable

                                           namespace GitLab.Client.SourceGenerators
                                           {
                                               /// <summary>How a multi-valued query parameter is written onto the query string.</summary>
                                               [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                                               internal enum QueryMultiValueStyle
                                               {
                                                   /// <summary>
                                                   /// One parameter whose value is a comma-separated list - OpenAPI "style: form, explode: false",
                                                   /// which is what every array query parameter in GitLab's spec declares.
                                                   /// </summary>
                                                   Comma = 0,

                                                   /// <summary>Repeated "name[]=a&amp;name[]=b", the form some GitLab doc pages show instead.</summary>
                                                   Repeated = 1
                                               }

                                               /// <summary>
                                               /// Marks an options type for compile-time generation of its
                                               /// <c>GitLabRouteBuilder.QueryFrom</c> overload. Every public readable property becomes one
                                               /// query parameter, named by snake_case of the property name unless [QueryParameter] says
                                               /// otherwise, and written in declaration order.
                                               /// </summary>
                                               /// <remarks>
                                               /// Targets both Class and Struct: the annotated type is a record today, but a
                                               /// <c>readonly record struct</c> is a struct declaration as far as attribute targeting is
                                               /// concerned, and restricting this to Class would make [GitLabQuery] inapplicable there
                                               /// (CS0592) before the generator itself ever gets a say.
                                               /// </remarks>
                                               [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                                               [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
                                               internal sealed class GitLabQueryAttribute : global::System.Attribute
                                               {
                                               }

                                               /// <summary>Overrides the snake_case-derived wire name and/or the multi-value style of one property.</summary>
                                               [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                                               [global::System.AttributeUsage(global::System.AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
                                               internal sealed class QueryParameterAttribute : global::System.Attribute
                                               {
                                                   public QueryParameterAttribute()
                                                   {
                                                   }

                                                   public QueryParameterAttribute(string name)
                                                   {
                                                       Name = name;
                                                   }

                                                   public string? Name { get; }

                                                   public QueryMultiValueStyle MultiValue { get; set; }
                                               }

                                               /// <summary>Excludes a property from the generated query-string projection.</summary>
                                               [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                                               [global::System.AttributeUsage(global::System.AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
                                               internal sealed class QueryIgnoreAttribute : global::System.Attribute
                                               {
                                               }
                                           }
                                           """;

    private static readonly DiagnosticDescriptor UnsupportedType = new(
        "GLQ0001",
        "Query option property type has no query-parameter mapping",
        "Property '{0}.{1}' of type '{2}' has no GitLab query-parameter mapping. Use string?, int?, long?, bool?, " +
        "DateTimeOffset?, DateOnly?, an enum annotated with [JsonConverter(typeof(JsonStringEnumConverter<T>))], " +
        "IReadOnlyList<string>? or IReadOnlyList<long>? - or mark the property [QueryIgnore].",
        Category,
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor NonNullableValueType = new(
        "GLQ0002",
        "Query option property must be nullable",
        "Property '{0}.{1}' is a non-nullable value type, so it has no 'not supplied' state and would always be " +
        "sent (e.g. per_page=0). Make it '{2}?' or mark it [QueryIgnore].",
        Category,
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor InvalidParameterName = new(
        "GLQ0003",
        "Invalid query-parameter name",
        "The query parameter for '{0}.{1}' resolves to '{2}'. A name must be non-empty and use only letters, " +
        "digits and _ - . [ ] $, and must not end with '[]' - QueryMultiValueStyle.Repeated appends that itself.",
        Category,
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor EnumMemberNotAnnotated = new(
        "GLQ0004",
        "Enum member has no explicit wire name",
        "Enum member '{0}.{1}' has no [JsonStringEnumMemberName]. Every member of an enum serialised as a string " +
        "must declare its wire value explicitly, so the query value and the JSON value cannot drift.",
        Category,
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor DuplicateParameterName = new(
        "GLQ0005",
        "Duplicate query-parameter name",
        "Properties '{0}' and '{1}' on '{2}' both map to the query parameter '{3}'",
        Category,
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor NoMappableProperties = new(
        "GLQ0006",
        "Type marked [GitLabQuery] contributes no query parameters",
        "'{0}' is marked [GitLabQuery] but has no mappable properties, so the generated QueryFrom overload does nothing",
        Category,
        DiagnosticSeverity.Info,
        true);

    private static readonly DiagnosticDescriptor RepeatedOnNonCollection = new(
        "GLQ0007",
        "QueryMultiValueStyle.Repeated requires a collection property",
        "Property '{0}.{1}' of type '{2}' asks for QueryMultiValueStyle.Repeated, which only applies to " +
        "IReadOnlyList<string>? and IReadOnlyList<long>?",
        Category,
        DiagnosticSeverity.Error,
        true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            // Safe to call from this second generator as well: Roslyn emits EmbeddedAttribute as an
            // "internal sealed PARTIAL class", so the copy added here merges with the one
            // GenerateClientLayersGenerator adds instead of colliding (CS0101).
            ctx.AddEmbeddedAttributeDefinition();
            ctx.AddSource("GitLabQueryAttributes.g.cs", SourceText.From(AttributeSource, Encoding.UTF8));
        });

        // The options types are records, so the syntactic filter has to be TypeDeclarationSyntax:
        // RecordDeclarationSyntax does NOT derive from ClassDeclarationSyntax.
        IncrementalValuesProvider<OptionsModel?> optionsTypes = context.SyntaxProvider.ForAttributeWithMetadataName(
            QueryAttributeFullName,
            static (node, _) => node is TypeDeclarationSyntax,
            static (ctx, _) => TryCreateOptionsModel(ctx));

        context.RegisterSourceOutput(optionsTypes, static (spc, model) =>
        {
            if (model is null)
            {
                return;
            }

            foreach (Diagnostic diagnostic in model.Diagnostics)
            {
                spc.ReportDiagnostic(diagnostic);
            }

            spc.AddSource($"{model.TypeName}QueryExtensions.g.cs",
                SourceText.From(RenderOptions(model), Encoding.UTF8));
        });

        IncrementalValuesProvider<EnumModel?> enums = context.SyntaxProvider.ForAttributeWithMetadataName(
            JsonConverterAttributeFullName,
            static (node, _) => node is EnumDeclarationSyntax,
            static (ctx, _) => TryCreateEnumModel(ctx));

        context.RegisterSourceOutput(enums, static (spc, model) =>
        {
            if (model is null)
            {
                return;
            }

            foreach (Diagnostic diagnostic in model.Diagnostics)
            {
                spc.ReportDiagnostic(diagnostic);
            }

            spc.AddSource($"{model.EnumName}QueryValues.g.cs", SourceText.From(RenderEnum(model), Encoding.UTF8));
        });
    }

    private static OptionsModel? TryCreateOptionsModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol optionsType)
        {
            return null;
        }

        OptionsModel model = new(optionsType.Name, Fqn(optionsType), optionsType.IsValueType);
        Dictionary<string, string> claimedNames = new(StringComparer.Ordinal);

        foreach (IPropertySymbol property in optionsType.GetMembers().OfType<IPropertySymbol>())
        {
            if (property.IsStatic || property.IsIndexer || property.GetMethod is null ||
                property.DeclaredAccessibility != Accessibility.Public ||
                HasAttribute(property, IgnoreAttributeFullName))
            {
                continue;
            }

            Location location = property.Locations.FirstOrDefault() ?? Location.None;
            AttributeData? overrideAttribute = FindAttribute(property, ParameterAttributeFullName);
            string? explicitName = overrideAttribute is { ConstructorArguments.Length: 1 }
                ? overrideAttribute.ConstructorArguments[0].Value as string
                : null;
            bool repeated = overrideAttribute is not null && overrideAttribute.NamedArguments.Any(static argument =>
                string.Equals(argument.Key, "MultiValue", StringComparison.Ordinal) &&
                argument.Value.Value is int style && style == 1);

            string wireName = explicitName ?? ToSnakeCase(property.Name);
            if (!IsValidParameterName(wireName) || wireName.EndsWith("[]", StringComparison.Ordinal))
            {
                model.Diagnostics.Add(Diagnostic.Create(
                    InvalidParameterName, location, optionsType.Name, property.Name, wireName));
                continue;
            }

            if (!TryClassify(property.Type, out QueryKind kind, out string? enumHelper))
            {
                DiagnosticDescriptor descriptor =
                    IsNonNullableValueType(property.Type) ? NonNullableValueType : UnsupportedType;
                model.Diagnostics.Add(Diagnostic.Create(
                    descriptor, location, optionsType.Name, property.Name, property.Type.ToDisplayString()));
                continue;
            }

            if (repeated && kind is not (QueryKind.StringList or QueryKind.Int64List))
            {
                model.Diagnostics.Add(Diagnostic.Create(
                    RepeatedOnNonCollection, location, optionsType.Name, property.Name,
                    property.Type.ToDisplayString()));
                continue;
            }

            if (claimedNames.TryGetValue(wireName, out string? previous))
            {
                model.Diagnostics.Add(Diagnostic.Create(
                    DuplicateParameterName, location, previous, property.Name, optionsType.Name, wireName));
                continue;
            }

            claimedNames.Add(wireName, property.Name);
            model.Properties.Add(new PropertyModel(property.Name, wireName, kind, enumHelper, repeated));
        }

        if (model.Properties.Count == 0 && model.Diagnostics.Count == 0)
        {
            model.Diagnostics.Add(Diagnostic.Create(
                NoMappableProperties, optionsType.Locations.FirstOrDefault() ?? Location.None, optionsType.Name));
        }

        return model;
    }

    /// <summary>
    ///     Maps a property's declared type onto one of the shapes <c>GitLabRouteBuilder</c> can write.
    ///     <para>
    ///         ProjectId/GroupId are deliberately absent. <c>ToRouteValue()</c> returns text that is
    ///         already percent-encoded, because the <c>Segment</c> overloads append it raw; routing it
    ///         through <c>Query</c> - which escapes what it is given - would turn <c>%2F</c> into
    ///         <c>%252F</c>. The two have deliberately opposite encoding contracts.
    ///     </para>
    /// </summary>
    private static bool TryClassify(ITypeSymbol type, out QueryKind kind, out string? enumHelper)
    {
        kind = QueryKind.String;
        enumHelper = null;

        ITypeSymbol underlying = UnwrapNullable(type);

        switch (underlying.SpecialType)
        {
            case SpecialType.System_String:
                kind = QueryKind.String;
                return true;
            case SpecialType.System_Int32:
                kind = QueryKind.Int32;
                return IsNullableOrReferenceType(type);
            case SpecialType.System_Int64:
                kind = QueryKind.Int64;
                return IsNullableOrReferenceType(type);
            case SpecialType.System_Boolean:
                kind = QueryKind.Boolean;
                return IsNullableOrReferenceType(type);
        }

        string display = underlying.ToDisplayString();
        if (string.Equals(display, DateTimeOffsetTypeName, StringComparison.Ordinal))
        {
            kind = QueryKind.DateTimeOffset;
            return IsNullableOrReferenceType(type);
        }

        if (string.Equals(display, DateOnlyTypeName, StringComparison.Ordinal))
        {
            kind = QueryKind.DateOnly;
            return IsNullableOrReferenceType(type);
        }

        if (underlying is INamedTypeSymbol { TypeKind: TypeKind.Enum } enumType)
        {
            if (!IsStringSerialisedEnum(enumType))
            {
                return false;
            }

            kind = QueryKind.Enum;
            enumHelper = $"global::{enumType.ContainingNamespace.ToDisplayString()}.{enumType.Name}QueryValues";
            return IsNullableOrReferenceType(type);
        }

        if (underlying is INamedTypeSymbol { IsGenericType: true } list && string.Equals(
                list.ConstructedFrom.ToDisplayString(), ReadOnlyListDefinition, StringComparison.Ordinal))
        {
            if (list.TypeArguments[0].SpecialType == SpecialType.System_String)
            {
                kind = QueryKind.StringList;
                return true;
            }

            if (list.TypeArguments[0].SpecialType == SpecialType.System_Int64)
            {
                kind = QueryKind.Int64List;
                return true;
            }
        }

        return false;
    }

    private static ITypeSymbol UnwrapNullable(ITypeSymbol type)
    {
        return type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } nullable
            ? nullable.TypeArguments[0]
            : type;
    }

    private static bool IsNullableOrReferenceType(ITypeSymbol type)
    {
        return !IsNonNullableValueType(type);
    }

    private static bool IsNonNullableValueType(ITypeSymbol type)
    {
        return type.IsValueType &&
               type is not INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T };
    }

    private static string RenderOptions(OptionsModel model)
    {
        StringBuilder builder = new();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.Append("namespace ").AppendLine(RoutingNamespace);
        builder.AppendLine("{");
        builder.Append("    internal static class ").Append(model.TypeName).AppendLine("QueryExtensions");
        builder.AppendLine("    {");
        builder.AppendLine("        /// <summary>");
        builder.AppendLine("        /// The wire names this type contributes, in order. Lets a test assert the exact");
        builder.AppendLine("        /// query-parameter spelling without reflecting over the options type.");
        builder.AppendLine("        /// </summary>");
        builder.Append("        internal const string QueryParameterNames = \"")
            .Append(string.Join(",", model.Properties.Select(static property => property.WireName)))
            .AppendLine("\";");
        builder.AppendLine();
        builder.Append("        public static ").Append(BuilderTypeName).AppendLine(" QueryFrom(");
        builder.Append("            this ").Append(BuilderTypeName).AppendLine(" builder,");
        builder.Append("            ").Append(model.FullyQualifiedType).AppendLine("? options)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (options is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return builder;");
        builder.AppendLine("            }");

        if (model.Properties.Count > 0)
        {
            builder.AppendLine();
        }

        // T? means Nullable<T> once T is a struct, and Nullable<T> does not forward member access to
        // T - "options.PropertyName" would not compile there. The null-check above still works
        // unchanged for both shapes (Nullable<T> supports comparison to null via its own equality); only
        // the property-access prefix needs to switch to "options.Value." for a value-typed T.
        string accessPrefix = model.IsValueType ? "options.Value." : "options.";

        foreach (PropertyModel property in model.Properties)
        {
            // Statements, not a fluent chain: an enum needs a helper call around the value, which a
            // chain would force into a nested conditional expression. Statements keep every shape
            // uniform and the emitted file readable in obj/Generated.
            string method = property.Repeated ? "QueryRepeated" : "Query";
            string argument = property.Kind == QueryKind.Enum
                ? $"{property.EnumHelper}.ToApiValue({accessPrefix}{property.PropertyName})"
                : $"{accessPrefix}{property.PropertyName}";

            builder.Append("            builder.").Append(method).Append("(\"").Append(property.WireName)
                .Append("\", ").Append(argument).AppendLine(");");
        }

        builder.AppendLine();
        builder.AppendLine("            return builder;");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static EnumModel? TryCreateEnumModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol { TypeKind: TypeKind.Enum } enumType ||
            !IsStringSerialisedEnum(enumType))
        {
            return null;
        }

        EnumModel model = new(enumType.Name, enumType.ContainingNamespace.ToDisplayString(), Fqn(enumType));
        HashSet<object> seenValues = new();

        foreach (IFieldSymbol member in enumType.GetMembers().OfType<IFieldSymbol>())
        {
            if (!member.HasConstantValue || member.ConstantValue is null || !seenValues.Add(member.ConstantValue))
            {
                // Aliases share a constant value, and two identical case labels would be CS0152.
                continue;
            }

            AttributeData? nameAttribute = FindAttribute(member, EnumMemberNameAttributeFullName);
            if (nameAttribute?.ConstructorArguments.FirstOrDefault().Value is not string wireValue)
            {
                model.Diagnostics.Add(Diagnostic.Create(
                    EnumMemberNotAnnotated, member.Locations.FirstOrDefault() ?? Location.None, enumType.Name,
                    member.Name));
                continue;
            }

            model.Members.Add(new EnumMemberModel(member.Name, wireValue));
        }

        return model;
    }

    private static string RenderEnum(EnumModel model)
    {
        StringBuilder builder = new();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.Append("namespace ").AppendLine(model.Namespace);
        builder.AppendLine("{");
        builder.Append("    internal static class ").Append(model.EnumName).AppendLine("QueryValues");
        builder.AppendLine("    {");
        builder.Append("        public static string ToApiValue(this ").Append(model.FullyQualifiedType)
            .AppendLine(" value)");
        builder.AppendLine("        {");
        builder.AppendLine("            switch (value)");
        builder.AppendLine("            {");

        foreach (EnumMemberModel member in model.Members)
        {
            builder.Append("                case ").Append(model.FullyQualifiedType).Append('.')
                .Append(member.MemberName).AppendLine(":");
            builder.Append("                    return \"").Append(member.WireValue).AppendLine("\";");
        }

        builder.AppendLine("                default:");
        builder.AppendLine(
            "                    throw new global::System.ArgumentOutOfRangeException(nameof(value), value, null);");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.Append("        public static string? ToApiValue(this ").Append(model.FullyQualifiedType)
            .AppendLine("? value)");
        builder.AppendLine("        {");
        builder.AppendLine("            return value is { } notNull ? ToApiValue(notNull) : null;");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static bool IsStringSerialisedEnum(INamedTypeSymbol enumType)
    {
        return FindAttribute(enumType, JsonConverterAttributeFullName)?.ConstructorArguments.FirstOrDefault().Value is
                   INamedTypeSymbol converterType &&
               string.Equals(converterType.OriginalDefinition.MetadataName, StringEnumConverterMetadataName,
                   StringComparison.Ordinal) &&
               string.Equals(converterType.ContainingNamespace.ToDisplayString(), JsonSerializationNamespace,
                   StringComparison.Ordinal);
    }

    private static AttributeData? FindAttribute(ISymbol symbol, string fullName)
    {
        return symbol.GetAttributes().FirstOrDefault(attribute =>
            attribute.AttributeClass is not null &&
            string.Equals(attribute.AttributeClass.ToDisplayString(), fullName, StringComparison.Ordinal));
    }

    private static bool HasAttribute(ISymbol symbol, string fullName)
    {
        return FindAttribute(symbol, fullName) is not null;
    }

    private static bool IsValidParameterName(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return false;
        }

        // Exactly the character set the 370 distinct query-parameter names in the vendored spec use.
        foreach (char character in name)
        {
            bool allowed = char.IsLetterOrDigit(character) || character == '_' || character == '-' ||
                           character == '.' || character == '[' || character == ']' || character == '$';
            if (!allowed)
            {
                return false;
            }
        }

        return true;
    }

    /// <summary>
    ///     PerPage -> per_page, OrderBy -> order_by, Ref -> ref, Sha256 -> sha256, CIProject -> ci_project.
    ///     The second condition is the acronym boundary: an upper-case character preceded by upper and
    ///     followed by lower starts a new word.
    /// </summary>
    private static string ToSnakeCase(string name)
    {
        StringBuilder builder = new(name.Length + 4);

        for (int i = 0; i < name.Length; i++)
        {
            char current = name[i];

            if (!char.IsUpper(current))
            {
                builder.Append(current);
                continue;
            }

            bool afterLowerOrDigit = i > 0 && (char.IsLower(name[i - 1]) || char.IsDigit(name[i - 1]));
            bool endsAcronym = i > 0 && i + 1 < name.Length && char.IsUpper(name[i - 1]) && char.IsLower(name[i + 1]);

            if (afterLowerOrDigit || endsAcronym)
            {
                builder.Append('_');
            }

            builder.Append(char.ToLowerInvariant(current));
        }

        return builder.ToString();
    }

    private static string Fqn(ITypeSymbol type)
    {
        return type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    }

    private enum QueryKind
    {
        String,
        Int32,
        Int64,
        Boolean,
        DateTimeOffset,
        DateOnly,
        Enum,
        StringList,
        Int64List
    }

    // Plain classes, not records: a record's generated equality would compare any symbol-typed member
    // with reference equality instead of SymbolEqualityComparer (RS1024). Same trade-off
    // GenerateClientLayersGenerator already documents and accepts.
    private sealed class OptionsModel(string typeName, string fullyQualifiedType, bool isValueType)
    {
        public string TypeName { get; } = typeName;

        public string FullyQualifiedType { get; } = fullyQualifiedType;

        /// <summary>
        ///     Whether the annotated type is a struct rather than a class/record. Drives whether the
        ///     generated <c>QueryFrom</c> accesses properties through <c>options.</c> (reference type,
        ///     where <c>T?</c> means nullable reference) or <c>options.Value.</c> (value type, where
        ///     <c>T?</c> means <see cref="System.Nullable{T}" />, which does not forward member access).
        /// </summary>
        public bool IsValueType { get; } = isValueType;

        public List<PropertyModel> Properties { get; } = new();

        public List<Diagnostic> Diagnostics { get; } = new();
    }

    private sealed class PropertyModel(
        string propertyName,
        string wireName,
        QueryKind kind,
        string? enumHelper,
        bool repeated)
    {
        public string PropertyName { get; } = propertyName;

        public string WireName { get; } = wireName;

        public QueryKind Kind { get; } = kind;

        public string? EnumHelper { get; } = enumHelper;

        public bool Repeated { get; } = repeated;
    }

    private sealed class EnumModel(string enumName, string namespaceName, string fullyQualifiedType)
    {
        public string EnumName { get; } = enumName;

        public string Namespace { get; } = namespaceName;

        public string FullyQualifiedType { get; } = fullyQualifiedType;

        public List<EnumMemberModel> Members { get; } = new();

        public List<Diagnostic> Diagnostics { get; } = new();
    }

    private sealed class EnumMemberModel(string memberName, string wireValue)
    {
        public string MemberName { get; } = memberName;

        public string WireValue { get; } = wireValue;
    }
}