using System.Text.Json;
using System.Text.Json.Serialization;

using GitLab.Client.Models;

namespace GitLab.Client.Infrastructure.Serialization;

// The single JsonSerializerContext for the whole library. Every [JsonSerializable] entry is
// hand-written on purpose: System.Text.Json's own generator runs against the original compilation
// and cannot see attributes contributed by another source generator, and the attributes cannot be
// spread across several partial declarations of this class either (that crashes the STJ generator
// with CS8785, "hintName ... must be unique within a generator"). See CLAUDE.md.
//
// Options deliberately left at their defaults - do not "improve" these without reading the note:
//
//   GenerationMode                     The default emits BOTH the metadata and the fast-path
//                                      serializer. Serialization alone would break every
//                                      deserialize call; the per-type
//                                      [JsonSerializable(..., GenerationMode = Metadata)] knob is
//                                      the size lever for response-only DTOs at spec scale.
//   AllowOutOfOrderMetadataProperties  Only affects $id/$type/$ref, which this library never emits
//                                      or reads. Enabling it forces the deserializer to buffer
//                                      whole objects, worst case O(n x d) in payload length/depth.
//   UnmappedMemberHandling             MUST stay Skip (the default). These DTOs model a deliberate
//                                      subset of each GitLab payload, so Disallow would throw on
//                                      practically every response.
//   UseStringEnumConverter             Redundant: each enum already carries the AOT-safe generic
//                                      [JsonConverter(typeof(JsonStringEnumConverter<T>))] plus
//                                      per-member [JsonStringEnumMemberName]. A blanket policy
//                                      would also silently break any future enum GitLab sends as an
//                                      integer (access levels, for one).
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    NumberHandling = JsonNumberHandling.AllowReadingFromString,
    // The public surface is nullable-annotated and carries no "!" suppressions, so enforce that
    // contract against the wire: an explicit "field": null for a non-nullable property becomes a
    // JsonException naming the property instead of a null smuggled into a non-nullable member that
    // only surfaces as an NRE deep in consumer code. Verified not to affect the outbound request
    // path: DefaultIgnoreCondition.WhenWritingNull is applied first, so a null non-nullable property
    // is omitted rather than throwing.
    RespectNullableAnnotations = true)]
[JsonSerializable(typeof(GitLabProject))]
[JsonSerializable(typeof(GitLabProject[]))]
[JsonSerializable(typeof(GitLabUser))]
[JsonSerializable(typeof(GitLabUser[]))]
[JsonSerializable(typeof(GitLabCommit))]
[JsonSerializable(typeof(GitLabCommit[]))]
[JsonSerializable(typeof(GitLabGroup))]
[JsonSerializable(typeof(GitLabGroup[]))]
[JsonSerializable(typeof(GitLabBranch))]
[JsonSerializable(typeof(GitLabBranch[]))]
[JsonSerializable(typeof(CreateBranchRequest))]
[JsonSerializable(typeof(GitLabIssue))]
[JsonSerializable(typeof(GitLabIssue[]))]
[JsonSerializable(typeof(CreateIssueRequest))]
[JsonSerializable(typeof(GitLabMergeRequest))]
[JsonSerializable(typeof(GitLabMergeRequest[]))]
[JsonSerializable(typeof(CreateMergeRequestRequest))]
[JsonSerializable(typeof(GitLabLabel))]
[JsonSerializable(typeof(GitLabLabel[]))]
[JsonSerializable(typeof(GitLabMilestone))]
[JsonSerializable(typeof(GitLabMilestone[]))]
[JsonSerializable(typeof(GitLabErrorResponse))]
[JsonSerializable(typeof(GitLabTag))]
[JsonSerializable(typeof(GitLabTag[]))]
[JsonSerializable(typeof(CreateTagRequest))]
[JsonSerializable(typeof(GitLabPipeline))]
[JsonSerializable(typeof(GitLabPipeline[]))]
[JsonSerializable(typeof(CreatePipelineRequest))]
[JsonSerializable(typeof(GitLabJob))]
[JsonSerializable(typeof(GitLabJob[]))]
[JsonSerializable(typeof(GitLabJobArtifact))]
[JsonSerializable(typeof(GitLabJobArtifact[]))]
[JsonSerializable(typeof(GitLabRepositoryFile))]
[JsonSerializable(typeof(CreateRepositoryFileRequest))]
[JsonSerializable(typeof(UpdateRepositoryFileRequest))]
[JsonSerializable(typeof(GitLabRelease))]
[JsonSerializable(typeof(GitLabRelease[]))]
[JsonSerializable(typeof(GitLabReleaseLinks))]
[JsonSerializable(typeof(CreateReleaseRequest))]
[JsonSerializable(typeof(GitLabProtectedBranch))]
[JsonSerializable(typeof(GitLabProtectedBranch[]))]
[JsonSerializable(typeof(GitLabAccessLevel))]
[JsonSerializable(typeof(ProtectBranchRequest))]
[JsonSerializable(typeof(GitLabEnvironment))]
[JsonSerializable(typeof(GitLabEnvironment[]))]
[JsonSerializable(typeof(CreateEnvironmentRequest))]
[JsonSerializable(typeof(GitLabNote))]
[JsonSerializable(typeof(GitLabNote[]))]
[JsonSerializable(typeof(CreateNoteRequest))]
[JsonSerializable(typeof(GitLabMember))]
[JsonSerializable(typeof(GitLabMember[]))]
[JsonSerializable(typeof(AddMemberRequest))]
[JsonSerializable(typeof(UpdateMemberRequest))]
[JsonSerializable(typeof(GitLabProjectHook))]
[JsonSerializable(typeof(GitLabProjectHook[]))]
[JsonSerializable(typeof(CreateProjectHookRequest))]
[JsonSerializable(typeof(UpdateProjectHookRequest))]
[JsonSerializable(typeof(GitLabDiscussion))]
[JsonSerializable(typeof(GitLabDiscussion[]))]
[JsonSerializable(typeof(CreateDiscussionRequest))]
[JsonSerializable(typeof(ResolveDiscussionRequest))]
[JsonSerializable(typeof(GitLabDraftNote))]
[JsonSerializable(typeof(GitLabDraftNote[]))]
[JsonSerializable(typeof(CreateDraftNoteRequest))]
[JsonSerializable(typeof(UpdateDraftNoteRequest))]
[JsonSerializable(typeof(PublishDraftNotesRequest))]
[JsonSerializable(typeof(GitLabSuggestion))]
[JsonSerializable(typeof(GitLabSuggestion[]))]
[JsonSerializable(typeof(ApplySuggestionRequest))]
[JsonSerializable(typeof(ApplySuggestionBatchRequest))]
[JsonSerializable(typeof(GitLabAwardEmoji))]
[JsonSerializable(typeof(GitLabAwardEmoji[]))]
[JsonSerializable(typeof(CreateAwardEmojiRequest))]
[JsonSerializable(typeof(GitLabTodo))]
[JsonSerializable(typeof(GitLabTodo[]))]
[JsonSerializable(typeof(GitLabProjectIdentity))]
[JsonSerializable(typeof(GitLabNamespace))]
[JsonSerializable(typeof(GitLabIteration))]
[JsonSerializable(typeof(GitLabIteration[]))]
[JsonSerializable(typeof(GitLabBoard))]
[JsonSerializable(typeof(GitLabBoard[]))]
[JsonSerializable(typeof(GitLabBoardList))]
[JsonSerializable(typeof(GitLabBoardList[]))]
[JsonSerializable(typeof(CreateBoardRequest))]
[JsonSerializable(typeof(UpdateBoardRequest))]
[JsonSerializable(typeof(CreateBoardListRequest))]
[JsonSerializable(typeof(UpdateBoardListRequest))]
[JsonSerializable(typeof(GitLabResourceLabelEvent))]
[JsonSerializable(typeof(GitLabResourceLabelEvent[]))]
[JsonSerializable(typeof(GitLabResourceStateEvent))]
[JsonSerializable(typeof(GitLabResourceStateEvent[]))]
[JsonSerializable(typeof(GitLabResourceMilestoneEvent))]
[JsonSerializable(typeof(GitLabResourceMilestoneEvent[]))]
[JsonSerializable(typeof(GitLabResourceIterationEvent))]
[JsonSerializable(typeof(GitLabResourceIterationEvent[]))]
[JsonSerializable(typeof(GitLabResourceWeightEvent))]
[JsonSerializable(typeof(GitLabResourceWeightEvent[]))]
[JsonSerializable(typeof(GitLabVariable))]
[JsonSerializable(typeof(GitLabVariable[]))]
[JsonSerializable(typeof(CreateVariableRequest))]
[JsonSerializable(typeof(UpdateVariableRequest))]
[JsonSerializable(typeof(GitLabTrigger))]
[JsonSerializable(typeof(GitLabTrigger[]))]
[JsonSerializable(typeof(CreateTriggerRequest))]
[JsonSerializable(typeof(UpdateTriggerRequest))]
[JsonSerializable(typeof(TriggerPipelineRequest))]
[JsonSerializable(typeof(GitLabCiLintResult))]
[JsonSerializable(typeof(GitLabCiLintInclude))]
[JsonSerializable(typeof(ValidateCiConfigurationRequest))]
[JsonSerializable(typeof(GitLabPipelineSchedule))]
[JsonSerializable(typeof(GitLabPipelineSchedule[]))]
[JsonSerializable(typeof(CreatePipelineScheduleRequest))]
[JsonSerializable(typeof(UpdatePipelineScheduleRequest))]
[JsonSerializable(typeof(GitLabRunner))]
[JsonSerializable(typeof(GitLabRunner[]))]
[JsonSerializable(typeof(UpdateRunnerRequest))]
[JsonSerializable(typeof(AssignRunnerRequest))]
[JsonSerializable(typeof(GitLabDeployment))]
[JsonSerializable(typeof(GitLabDeployment[]))]
[JsonSerializable(typeof(GitLabDeploymentApproval))]
[JsonSerializable(typeof(CreateDeploymentRequest))]
[JsonSerializable(typeof(UpdateDeploymentRequest))]
[JsonSerializable(typeof(ApproveDeploymentRequest))]
[JsonSerializable(typeof(GitLabDeployKey))]
[JsonSerializable(typeof(GitLabDeployKey[]))]
[JsonSerializable(typeof(CreateDeployKeyRequest))]
[JsonSerializable(typeof(UpdateDeployKeyRequest))]
[JsonSerializable(typeof(GitLabCommitStatus))]
[JsonSerializable(typeof(GitLabCommitStatus[]))]
[JsonSerializable(typeof(CreateCommitStatusRequest))]
[JsonSerializable(typeof(GitLabTreeItem))]
[JsonSerializable(typeof(GitLabTreeItem[]))]
[JsonSerializable(typeof(GitLabCompare))]
[JsonSerializable(typeof(GitLabDiff))]
[JsonSerializable(typeof(GitLabDiff[]))]
[JsonSerializable(typeof(GitLabContributor))]
[JsonSerializable(typeof(GitLabContributor[]))]
[JsonSerializable(typeof(GitLabDiffStat))]
[JsonSerializable(typeof(GitLabDiffStat[]))]
[JsonSerializable(typeof(GitLabChangedPath))]
[JsonSerializable(typeof(GitLabChangedPath[]))]
[JsonSerializable(typeof(GitLabDivergingCommitCount))]
[JsonSerializable(typeof(GitLabChangelog))]
[JsonSerializable(typeof(GitLabWikiPage))]
[JsonSerializable(typeof(GitLabWikiPage[]))]
[JsonSerializable(typeof(CreateWikiPageRequest))]
[JsonSerializable(typeof(UpdateWikiPageRequest))]
[JsonSerializable(typeof(GitLabBadge))]
[JsonSerializable(typeof(GitLabBadge[]))]
[JsonSerializable(typeof(GitLabBadgePreview))]
[JsonSerializable(typeof(CreateBadgeRequest))]
[JsonSerializable(typeof(UpdateBadgeRequest))]
[JsonSerializable(typeof(GitLabEvent))]
[JsonSerializable(typeof(GitLabEvent[]))]
[JsonSerializable(typeof(GitLabPushEventPayload))]
[JsonSerializable(typeof(GitLabProtectedTag))]
[JsonSerializable(typeof(GitLabProtectedTag[]))]
[JsonSerializable(typeof(ProtectTagRequest))]
[JsonSerializable(typeof(GitLabRemoteMirror))]
[JsonSerializable(typeof(GitLabRemoteMirror[]))]
[JsonSerializable(typeof(GitLabMirrorHostKey))]
[JsonSerializable(typeof(CreateRemoteMirrorRequest))]
[JsonSerializable(typeof(UpdateRemoteMirrorRequest))]
[JsonSerializable(typeof(UpdateEnvironmentRequest))]
[JsonSerializable(typeof(StopEnvironmentRequest))]
[JsonSerializable(typeof(GitLabAccessToken))]
[JsonSerializable(typeof(GitLabAccessToken[]))]
[JsonSerializable(typeof(GitLabGranularScope))]
[JsonSerializable(typeof(CreateAccessTokenRequest))]
[JsonSerializable(typeof(RotateAccessTokenRequest))]
[JsonSerializable(typeof(GitLabPersonalAccessToken))]
[JsonSerializable(typeof(GitLabPersonalAccessToken[]))]
[JsonSerializable(typeof(CreatePersonalAccessTokenRequest))]
[JsonSerializable(typeof(GitLabSshKey))]
[JsonSerializable(typeof(GitLabSshKey[]))]
[JsonSerializable(typeof(CreateSshKeyRequest))]
[JsonSerializable(typeof(GitLabMergeRequestApprovals))]
[JsonSerializable(typeof(GitLabApproval))]
[JsonSerializable(typeof(GitLabMergeRequestApprovalState))]
[JsonSerializable(typeof(GitLabMergeRequestApprovalRule))]
[JsonSerializable(typeof(GitLabMergeRequestApprovalRule[]))]
[JsonSerializable(typeof(GitLabApprovalSourceRule))]
[JsonSerializable(typeof(ApproveMergeRequestRequest))]
[JsonSerializable(typeof(CreateMergeRequestApprovalRuleRequest))]
[JsonSerializable(typeof(UpdateMergeRequestApprovalRuleRequest))]
[JsonSerializable(typeof(GitLabApprovalRule))]
[JsonSerializable(typeof(GitLabApprovalRule[]))]
[JsonSerializable(typeof(CreateApprovalRuleRequest))]
[JsonSerializable(typeof(UpdateApprovalRuleRequest))]
[JsonSerializable(typeof(GitLabExternalStatusCheck))]
[JsonSerializable(typeof(GitLabExternalStatusCheck[]))]
[JsonSerializable(typeof(GitLabMergeRequestStatusCheck))]
[JsonSerializable(typeof(GitLabMergeRequestStatusCheck[]))]
[JsonSerializable(typeof(GitLabStatusCheckResponse))]
[JsonSerializable(typeof(GitLabStatusCheckSummary))]
[JsonSerializable(typeof(CreateExternalStatusCheckRequest))]
[JsonSerializable(typeof(UpdateExternalStatusCheckRequest))]
[JsonSerializable(typeof(SetStatusCheckStatusRequest))]
[JsonSerializable(typeof(GitLabAccessRequest))]
[JsonSerializable(typeof(GitLabAccessRequest[]))]
[JsonSerializable(typeof(ApproveAccessRequestRequest))]
[JsonSerializable(typeof(GitLabInvitation))]
[JsonSerializable(typeof(GitLabInvitation[]))]
[JsonSerializable(typeof(CreateInvitationRequest))]
[JsonSerializable(typeof(UpdateInvitationRequest))]
[JsonSerializable(typeof(GitLabProtectedEnvironment))]
[JsonSerializable(typeof(GitLabProtectedEnvironment[]))]
[JsonSerializable(typeof(GitLabDeployAccessLevel))]
[JsonSerializable(typeof(GitLabProtectedEnvironmentApprovalRule))]
[JsonSerializable(typeof(ProtectEnvironmentRequest))]
[JsonSerializable(typeof(UpdateProtectedEnvironmentRequest))]
[JsonSerializable(typeof(DeployAccessLevelRequest))]
[JsonSerializable(typeof(ProtectedEnvironmentApprovalRuleRequest))]
[JsonSerializable(typeof(GitLabGpgKey))]
[JsonSerializable(typeof(GitLabGpgKey[]))]
[JsonSerializable(typeof(CreateGpgKeyRequest))]
[JsonSerializable(typeof(GitLabSshCertificate))]
[JsonSerializable(typeof(GitLabSshCertificate[]))]
[JsonSerializable(typeof(CreateSshCertificateRequest))]
[JsonSerializable(typeof(UpdateNoteRequest))]
[JsonSerializable(typeof(GitLabFreezePeriod))]
[JsonSerializable(typeof(GitLabFreezePeriod[]))]
[JsonSerializable(typeof(CreateFreezePeriodRequest))]
[JsonSerializable(typeof(UpdateFreezePeriodRequest))]
[JsonSerializable(typeof(GitLabResourceGroup))]
[JsonSerializable(typeof(GitLabResourceGroup[]))]
[JsonSerializable(typeof(UpdateResourceGroupRequest))]
[JsonSerializable(typeof(GitLabMergeTrainCar))]
[JsonSerializable(typeof(GitLabMergeTrainCar[]))]
[JsonSerializable(typeof(GitLabMergeTrainMergeRequest))]
[JsonSerializable(typeof(AddToMergeTrainRequest))]
[JsonSerializable(typeof(GitLabSecureFile))]
[JsonSerializable(typeof(GitLabSecureFile[]))]
[JsonSerializable(typeof(GitLabRunnerManager))]
[JsonSerializable(typeof(GitLabRunnerManager[]))]
[JsonSerializable(typeof(GitLabRunnerToken))]
[JsonSerializable(typeof(GitLabRunnerController))]
[JsonSerializable(typeof(GitLabRunnerController[]))]
[JsonSerializable(typeof(GitLabRunnerControllerScope))]
[JsonSerializable(typeof(GitLabRunnerControllerScope[]))]
[JsonSerializable(typeof(GitLabRunnerControllerToken))]
[JsonSerializable(typeof(GitLabRunnerControllerToken[]))]
[JsonSerializable(typeof(GitLabRunnerControllerTokenWithSecret))]
[JsonSerializable(typeof(RegisterRunnerControllerRequest))]
[JsonSerializable(typeof(UpdateRunnerControllerRequest))]
[JsonSerializable(typeof(CreateRunnerControllerTokenRequest))]
[JsonSerializable(typeof(GitLabAccessTokenWithSecret))]
[JsonSerializable(typeof(GitLabPersonalAccessTokenWithSecret))]
[JsonSerializable(typeof(GitLabImpersonationToken))]
[JsonSerializable(typeof(GitLabImpersonationToken[]))]
[JsonSerializable(typeof(GitLabImpersonationTokenWithSecret))]
[JsonSerializable(typeof(GitLabTokenAssociations))]
[JsonSerializable(typeof(GitLabTokenAssociationGroup))]
[JsonSerializable(typeof(GitLabTokenAssociationProject))]
[JsonSerializable(typeof(CreateCurrentUserPersonalAccessTokenRequest))]
[JsonSerializable(typeof(CreateImpersonationTokenRequest))]
[JsonSerializable(typeof(GitLabHookUrlVariable))]
[JsonSerializable(typeof(GitLabHookCustomHeader))]
[JsonSerializable(typeof(GitLabGroupHook))]
[JsonSerializable(typeof(GitLabGroupHook[]))]
[JsonSerializable(typeof(GitLabSystemHook))]
[JsonSerializable(typeof(GitLabSystemHook[]))]
[JsonSerializable(typeof(GitLabHookEvent))]
[JsonSerializable(typeof(GitLabHookEvent[]))]
[JsonSerializable(typeof(CreateGroupHookRequest))]
[JsonSerializable(typeof(UpdateGroupHookRequest))]
[JsonSerializable(typeof(CreateSystemHookRequest))]
[JsonSerializable(typeof(UpdateSystemHookRequest))]
[JsonSerializable(typeof(GitLabProjectApprovalSettings))]
[JsonSerializable(typeof(GitLabProjectApprovalSettingRule))]
[JsonSerializable(typeof(GitLabProjectApprovalConfiguration))]
[JsonSerializable(typeof(GitLabApprover))]
[JsonSerializable(typeof(GitLabApproverGroup))]
[JsonSerializable(typeof(SetApprovalConfigurationRequest))]
[JsonSerializable(typeof(GitLabMergeRequestApprovalSetting))]
[JsonSerializable(typeof(UpdateMergeRequestApprovalSettingRequest))]
[JsonSerializable(typeof(AddGroupMemberRequest))]
[JsonSerializable(typeof(UpdateGroupMemberRequest))]
[JsonSerializable(typeof(GitLabPendingMember))]
[JsonSerializable(typeof(GitLabPendingMember[]))]
[JsonSerializable(typeof(GitLabBillableMembership))]
[JsonSerializable(typeof(GitLabBillableMembership[]))]
[JsonSerializable(typeof(GitLabBillableMembershipAccessLevel))]
[JsonSerializable(typeof(GitLabNotePosition))]
[JsonSerializable(typeof(GitLabNoteLineRange))]
[JsonSerializable(typeof(GitLabNoteLinePosition))]
[JsonSerializable(typeof(CreateDiscussionNoteRequest))]
[JsonSerializable(typeof(UpdateDiscussionNoteRequest))]
[JsonSerializable(typeof(GitLabGroupLabel))]
[JsonSerializable(typeof(GitLabGroupLabel[]))]
[JsonSerializable(typeof(CreateLabelRequest))]
[JsonSerializable(typeof(UpdateLabelRequest))]
[JsonSerializable(typeof(CreateGroupLabelRequest))]
[JsonSerializable(typeof(UpdateGroupLabelRequest))]
[JsonSerializable(typeof(UpdateGroupLabelByIdRequest))]
[JsonSerializable(typeof(GitLabBurndownEvent))]
[JsonSerializable(typeof(GitLabBurndownEvent[]))]
[JsonSerializable(typeof(CreateMilestoneRequest))]
[JsonSerializable(typeof(UpdateMilestoneRequest))]
[JsonSerializable(typeof(GitLabProjectRepositoryStorageMove))]
[JsonSerializable(typeof(GitLabProjectRepositoryStorageMove[]))]
[JsonSerializable(typeof(GitLabGroupRepositoryStorageMove))]
[JsonSerializable(typeof(GitLabGroupRepositoryStorageMove[]))]
[JsonSerializable(typeof(GitLabSnippetRepositoryStorageMove))]
[JsonSerializable(typeof(GitLabSnippetRepositoryStorageMove[]))]
[JsonSerializable(typeof(GitLabStorageMoveGroup))]
[JsonSerializable(typeof(GitLabStorageMoveSnippet))]
[JsonSerializable(typeof(CreateStorageMoveRequest))]
[JsonSerializable(typeof(ScheduleStorageShardMovesRequest))]
[JsonSerializable(typeof(GitLabServiceAccount))]
[JsonSerializable(typeof(GitLabServiceAccount[]))]
[JsonSerializable(typeof(CreateServiceAccountRequest))]
[JsonSerializable(typeof(UpdateServiceAccountRequest))]
[JsonSerializable(typeof(GitLabMemberRole))]
[JsonSerializable(typeof(GitLabMemberRole[]))]
[JsonSerializable(typeof(CreateMemberRoleRequest))]
[JsonSerializable(typeof(CreateAdminMemberRoleRequest))]
[JsonSerializable(typeof(GitLabAvatar))]
[JsonSerializable(typeof(GitLabUserActivity))]
[JsonSerializable(typeof(GitLabUserActivity[]))]
[JsonSerializable(typeof(GitLabEmail))]
[JsonSerializable(typeof(GitLabEmail[]))]
[JsonSerializable(typeof(AddCurrentUserEmailRequest))]
[JsonSerializable(typeof(GitLabUserPreferences))]
[JsonSerializable(typeof(UpdateUserPreferencesRequest))]
[JsonSerializable(typeof(GitLabUserStatus))]
[JsonSerializable(typeof(SetUserStatusRequest))]
[JsonSerializable(typeof(GitLabSupportPin))]
[JsonSerializable(typeof(GitLabRunnerRegistration))]
[JsonSerializable(typeof(CreateUserRunnerRequest))]
[JsonSerializable(typeof(GitLabSnippet))]
[JsonSerializable(typeof(GitLabSnippet[]))]
[JsonSerializable(typeof(GitLabSnippetFile))]
[JsonSerializable(typeof(CreateSnippetRequest))]
[JsonSerializable(typeof(CreateSnippetFileRequest))]
[JsonSerializable(typeof(UpdateSnippetRequest))]
[JsonSerializable(typeof(UpdateSnippetFileRequest))]
[JsonSerializable(typeof(GitLabUserAgentDetail))]
[JsonSerializable(typeof(GitLabUploadAuthor))]
[JsonSerializable(typeof(GitLabProjectUpload))]
[JsonSerializable(typeof(GitLabProjectUpload[]))]
[JsonSerializable(typeof(GitLabProjectUploadLink))]
[JsonSerializable(typeof(GitLabTerraformStateProtectionRule))]
[JsonSerializable(typeof(GitLabTerraformStateProtectionRule[]))]
[JsonSerializable(typeof(CreateTerraformStateProtectionRuleRequest))]
[JsonSerializable(typeof(UpdateTerraformStateProtectionRuleRequest))]
[JsonSerializable(typeof(LockTerraformStateRequest))]
[JsonSerializable(typeof(GitLabAgentIdentity))]
[JsonSerializable(typeof(GitLabAgentSession))]
[JsonSerializable(typeof(GitLabAgentSession[]))]
[JsonSerializable(typeof(RegisterAgentIdentityRequest))]
[JsonSerializable(typeof(CreateAgentSessionRequest))]
[JsonSerializable(typeof(CompleteAgentSessionRequest))]
[JsonSerializable(typeof(IngestAgentAuditEventsRequest))]
[JsonSerializable(typeof(UpdateReleaseRequest))]
[JsonSerializable(typeof(GitLabReleaseLink))]
[JsonSerializable(typeof(GitLabReleaseLink[]))]
[JsonSerializable(typeof(GitLabReleaseSource))]
[JsonSerializable(typeof(GitLabReleaseAssets))]
[JsonSerializable(typeof(GitLabReleaseEvidence))]
[JsonSerializable(typeof(CreateReleaseLinkRequest))]
[JsonSerializable(typeof(UpdateReleaseLinkRequest))]
[JsonSerializable(typeof(StopStaleEnvironmentsRequest))]
[JsonSerializable(typeof(ProtectedBranchAccessRequest))]
[JsonSerializable(typeof(UpdateProtectedBranchRequest))]
[JsonSerializable(typeof(GitLabTestReport))]
[JsonSerializable(typeof(GitLabTestReportSummary))]
[JsonSerializable(typeof(GitLabTestReportTotal))]
[JsonSerializable(typeof(GitLabTestSuite))]
[JsonSerializable(typeof(GitLabTestCase))]
[JsonSerializable(typeof(GitLabTestCaseRecentFailures))]
[JsonSerializable(typeof(UpdatePipelineMetadataRequest))]
[JsonSerializable(typeof(CreatePipelineScheduleVariableRequest))]
[JsonSerializable(typeof(UpdatePipelineScheduleVariableRequest))]
[JsonSerializable(typeof(GitLabJobArtifactEntry))]
[JsonSerializable(typeof(GitLabJobArtifactEntry[]))]
[JsonSerializable(typeof(GitLabUserIdentity))]
[JsonSerializable(typeof(GitLabUserCounts))]
[JsonSerializable(typeof(GitLabUserAssociationsCount))]
[JsonSerializable(typeof(GitLabUserSupportPin))]
[JsonSerializable(typeof(GitLabUserMembership))]
[JsonSerializable(typeof(GitLabUserMembership[]))]
[JsonSerializable(typeof(CreateUserRequest))]
[JsonSerializable(typeof(UpdateUserRequest))]
[JsonSerializable(typeof(AddUserEmailRequest))]
[JsonSerializable(typeof(CreateGroupRequest))]
[JsonSerializable(typeof(UpdateGroupRequest))]
[JsonSerializable(typeof(ShareGroupRequest))]
[JsonSerializable(typeof(TransferGroupRequest))]
[JsonSerializable(typeof(TransferGroupToOrganizationRequest))]
[JsonSerializable(typeof(GitLabDefaultBranchProtectionDefaults))]
[JsonSerializable(typeof(GitLabGroupStatistics))]
[JsonSerializable(typeof(GitLabSharedGroupLink))]
[JsonSerializable(typeof(GitLabBillableMember))]
[JsonSerializable(typeof(GitLabBillableMember[]))]
[JsonSerializable(typeof(GitLabGroupUpload))]
[JsonSerializable(typeof(GitLabGroupUpload[]))]
[JsonSerializable(typeof(GitLabGroupUploadedFile))]
[JsonSerializable(typeof(GitLabGroupIssueStatistics))]
[JsonSerializable(typeof(GitLabGroupIssueStatisticsBreakdown))]
[JsonSerializable(typeof(GitLabGroupIssueCounts))]
[JsonSerializable(typeof(GitLabCommitStats))]
[JsonSerializable(typeof(CommitAction))]
[JsonSerializable(typeof(CreateCommitRequest))]
[JsonSerializable(typeof(CherryPickCommitRequest))]
[JsonSerializable(typeof(RevertCommitRequest))]
[JsonSerializable(typeof(GitLabCommitComment))]
[JsonSerializable(typeof(GitLabCommitComment[]))]
[JsonSerializable(typeof(CreateCommitCommentRequest))]
[JsonSerializable(typeof(GitLabCommitRef))]
[JsonSerializable(typeof(GitLabCommitRef[]))]
[JsonSerializable(typeof(GitLabCommitSequence))]
[JsonSerializable(typeof(GitLabCommitSignature))]
[JsonSerializable(typeof(GitLabTagSignature))]
[JsonSerializable(typeof(GitLabX509Certificate))]
[JsonSerializable(typeof(GitLabX509Issuer))]
[JsonSerializable(typeof(GitLabWebCommitsPublicKey))]
[JsonSerializable(typeof(ProtectSingleBranchRequest))]
[JsonSerializable(typeof(UnprotectBranchRequest))]
[JsonSerializable(typeof(GitLabBlameCommit))]
[JsonSerializable(typeof(GitLabBlameRange))]
[JsonSerializable(typeof(GitLabBlameRange[]))]
[JsonSerializable(typeof(GitLabBlob))]
[JsonSerializable(typeof(GitLabBatchBlob))]
[JsonSerializable(typeof(GitLabBatchBlob[]))]
[JsonSerializable(typeof(BlobBatchFile))]
[JsonSerializable(typeof(BlobBatchRequest))]
[JsonSerializable(typeof(AddChangelogRequest))]
[JsonSerializable(typeof(UpdateSubmoduleRequest))]
[JsonSerializable(typeof(GitLabRepositoryHealth))]
[JsonSerializable(typeof(GitLabRepositoryHealthReferences))]
[JsonSerializable(typeof(GitLabRepositoryHealthObjects))]
[JsonSerializable(typeof(GitLabRepositoryHealthCommitGraph))]
[JsonSerializable(typeof(GitLabRepositoryHealthBitmap))]
[JsonSerializable(typeof(GitLabRepositoryHealthMultiPackIndex))]
[JsonSerializable(typeof(GitLabRepositoryHealthLastFullRepack))]
[JsonSerializable(typeof(CreateProjectRequest))]
[JsonSerializable(typeof(UpdateProjectRequest))]
[JsonSerializable(typeof(ContainerExpirationPolicyAttributes))]
[JsonSerializable(typeof(ForkProjectRequest))]
[JsonSerializable(typeof(ShareProjectRequest))]
[JsonSerializable(typeof(TransferProjectRequest))]
[JsonSerializable(typeof(ProjectHousekeepingRequest))]
[JsonSerializable(typeof(UpdateProjectSecuritySettingsRequest))]
[JsonSerializable(typeof(GitLabProjectSecuritySettings))]
[JsonSerializable(typeof(GitLabProjectGroupLink))]
[JsonSerializable(typeof(GitLabPublicGroupDetails))]
[JsonSerializable(typeof(GitLabPublicGroupDetails[]))]
[JsonSerializable(typeof(GitLabProjectStarrer))]
[JsonSerializable(typeof(GitLabProjectStarrer[]))]
[JsonSerializable(typeof(GitLabProjectStorage))]
[JsonSerializable(typeof(GitLabProjectDailyStatistics))]
[JsonSerializable(typeof(GitLabProjectFetchStatistics))]
[JsonSerializable(typeof(GitLabProjectDailyFetchCount))]
[JsonSerializable(typeof(GitLabProjectAuditEvent))]
[JsonSerializable(typeof(GitLabProjectAuditEvent[]))]
// GET /projects/:id/languages answers with a bare map of language name to percentage of the
// repository, so the root type is the dictionary itself. TypeInfoPropertyName is set because the
// generator's derived name for a constructed generic is neither obvious nor stable to read.
[JsonSerializable(typeof(IReadOnlyDictionary<string, double>), TypeInfoPropertyName = "ProjectLanguages")]
[JsonSerializable(typeof(UpdateIssueRequest))]
[JsonSerializable(typeof(MoveIssueRequest))]
[JsonSerializable(typeof(CloneIssueRequest))]
[JsonSerializable(typeof(ReorderIssueRequest))]
[JsonSerializable(typeof(CreateIssueLinkRequest))]
[JsonSerializable(typeof(SetIssueTimeEstimateRequest))]
[JsonSerializable(typeof(AddIssueSpentTimeRequest))]
[JsonSerializable(typeof(UpdateMetricImageRequest))]
[JsonSerializable(typeof(GitLabIssueLink))]
[JsonSerializable(typeof(GitLabTimeStats))]
[JsonSerializable(typeof(GitLabTaskCompletionStatus))]
[JsonSerializable(typeof(GitLabIssuableReferences))]
[JsonSerializable(typeof(GitLabMetricImage))]
[JsonSerializable(typeof(GitLabMetricImage[]))]
[JsonSerializable(typeof(GitLabIssueStatistics))]
[JsonSerializable(typeof(GitLabIssueStatisticsSummary))]
[JsonSerializable(typeof(GitLabIssueCounts))]
[JsonSerializable(typeof(GitLabMergeRequestDiffVersion))]
[JsonSerializable(typeof(GitLabMergeRequestDiffVersion[]))]
[JsonSerializable(typeof(GitLabMergeRequestDependency))]
[JsonSerializable(typeof(GitLabMergeRequestDependency[]))]
[JsonSerializable(typeof(GitLabMergeRequestReviewer))]
[JsonSerializable(typeof(GitLabMergeRequestReviewer[]))]
[JsonSerializable(typeof(GitLabMergeRequestMergeRef))]
[JsonSerializable(typeof(GitLabMergeRequestRebaseResult))]
[JsonSerializable(typeof(UpdateMergeRequestRequest))]
[JsonSerializable(typeof(MergeMergeRequestRequest))]
[JsonSerializable(typeof(RebaseMergeRequestRequest))]
[JsonSerializable(typeof(MergeRequestTimeEstimateRequest))]
[JsonSerializable(typeof(MergeRequestSpentTimeRequest))]
[JsonSerializable(typeof(CreateMergeRequestContextCommitsRequest))]
[JsonSerializable(typeof(CreateMergeRequestPipelineRequest))]
[JsonSerializable(typeof(CreateMergeRequestDependencyRequest))]
[JsonSerializable(typeof(GitLabLicense))]
[JsonSerializable(typeof(GitLabLicense[]))]
[JsonSerializable(typeof(CreateLicenseRequest))]
[JsonSerializable(typeof(GitLabLicenseRefreshResult))]
[JsonSerializable(typeof(GitLabManagedLicense))]
[JsonSerializable(typeof(GitLabManagedLicense[]))]
[JsonSerializable(typeof(CreateManagedLicenseRequest))]
[JsonSerializable(typeof(UpdateManagedLicenseRequest))]
[JsonSerializable(typeof(GitLabDependency))]
[JsonSerializable(typeof(GitLabDependency[]))]
[JsonSerializable(typeof(GitLabDependencyLicense))]
[JsonSerializable(typeof(GitLabDependencyVulnerability))]
[JsonSerializable(typeof(GitLabDependencyVulnerability[]))]
[JsonSerializable(typeof(GitLabDependencyListExport))]
[JsonSerializable(typeof(CreateProjectDependencyListExportRequest))]
[JsonSerializable(typeof(CreateGroupDependencyListExportRequest))]
[JsonSerializable(typeof(CreatePipelineDependencyListExportRequest))]
[JsonSerializable(typeof(GitLabAttestation))]
[JsonSerializable(typeof(GitLabAttestation[]))]
[JsonSerializable(typeof(SastFileScanRequest))]
// ScanFileAsync's response uses the root JsonElement registration further down this file (see the
// note there) rather than a second one here - duplicate [JsonSerializable(typeof(JsonElement))]
// attributes is a compile error.
[JsonSerializable(typeof(AuthorizeSbomScanUploadRequest))]
[JsonSerializable(typeof(ReuseSbomScanRequest))]
[JsonSerializable(typeof(GitLabSbomScan))]
[JsonSerializable(typeof(GitLabJiraConnectResult))]
[JsonSerializable(typeof(GitLabJiraConnectSubscription))]
[JsonSerializable(typeof(GitLabJiraConnectSubscription[]))]
[JsonSerializable(typeof(GitLabJiraConnectGroup))]
[JsonSerializable(typeof(SubscribeJiraConnectNamespaceRequest))]
[JsonSerializable(typeof(CreateJiraForgeSubscriptionRequest))]
[JsonSerializable(typeof(UpdateJiraForgeInstallationRequest))]
[JsonSerializable(typeof(GitLabMlModel))]
[JsonSerializable(typeof(GitLabMlModelVersion))]
[JsonSerializable(typeof(GitLabMlModelTag))]
[JsonSerializable(typeof(GitLabMlModelSearchResult))]
[JsonSerializable(typeof(CreateMlModelRequest))]
[JsonSerializable(typeof(UpdateMlModelRequest))]
[JsonSerializable(typeof(MlModelLatestVersionsRequest))]
[JsonSerializable(typeof(GitLabPagesSettings))]
[JsonSerializable(typeof(UpdatePagesSettingsRequest))]
[JsonSerializable(typeof(GitLabPagesDeployment))]
[JsonSerializable(typeof(GitLabPagesDomain))]
[JsonSerializable(typeof(GitLabPagesDomain[]))]
[JsonSerializable(typeof(GitLabPagesDomainCertificate))]
[JsonSerializable(typeof(GitLabPagesDomainSummary))]
[JsonSerializable(typeof(GitLabPagesDomainSummary[]))]
[JsonSerializable(typeof(GitLabPagesDomainCertificateExpiration))]
[JsonSerializable(typeof(CreatePagesDomainRequest))]
[JsonSerializable(typeof(UpdatePagesDomainRequest))]
[JsonSerializable(typeof(GitLabCustomAttribute))]
[JsonSerializable(typeof(GitLabCustomAttribute[]))]
[JsonSerializable(typeof(SetCustomAttributeRequest))]
[JsonSerializable(typeof(GitLabTopic))]
[JsonSerializable(typeof(GitLabTopic[]))]
[JsonSerializable(typeof(CreateTopicRequest))]
[JsonSerializable(typeof(UpdateTopicRequest))]
[JsonSerializable(typeof(MergeTopicsRequest))]
[JsonSerializable(typeof(GitLabProjectAlias))]
[JsonSerializable(typeof(GitLabProjectAlias[]))]
[JsonSerializable(typeof(CreateProjectAliasRequest))]
[JsonSerializable(typeof(GitLabDeployToken))]
[JsonSerializable(typeof(GitLabDeployToken[]))]
[JsonSerializable(typeof(GitLabDeployTokenWithSecret))]
[JsonSerializable(typeof(CreateDeployTokenRequest))]
[JsonSerializable(typeof(GitLabProviderIdentity))]
[JsonSerializable(typeof(GitLabProviderIdentity[]))]
[JsonSerializable(typeof(UpdateProviderIdentityRequest))]
[JsonSerializable(typeof(GitLabSamlGroupLink))]
[JsonSerializable(typeof(GitLabSamlGroupLink[]))]
[JsonSerializable(typeof(CreateSamlGroupLinkRequest))]
[JsonSerializable(typeof(GitLabIntegration))]
[JsonSerializable(typeof(GitLabIntegration[]))]
[JsonSerializable(typeof(SlackEventRequest))]
[JsonSerializable(typeof(TriggerSlackCommandRequest))]
[JsonSerializable(typeof(TriggerMattermostSlashCommandRequest))]
// The untyped escape hatch for an integration with no typed settings record yet: PUT
// /projects/:id/integrations/:slug takes a flat property bag, and the keys are GitLab's own
// snake_case parameter names, which DictionaryKeyPolicy (unset) passes through verbatim. Written
// fully qualified so this append never has to touch the using block at the top of a merge=union file.
[JsonSerializable(typeof(IReadOnlyDictionary<string, JsonElement>),
    TypeInfoPropertyName = "IntegrationSettings")]
[JsonSerializable(typeof(GitLabTemplateSummary))]
[JsonSerializable(typeof(GitLabTemplateSummary[]))]
[JsonSerializable(typeof(GitLabTemplate))]
[JsonSerializable(typeof(GitLabLicenseTemplate))]
[JsonSerializable(typeof(GitLabLicenseTemplate[]))]
[JsonSerializable(typeof(GitLabVsCodeSettingsManifest))]
[JsonSerializable(typeof(GitLabVsCodeSetting))]
[JsonSerializable(typeof(GitLabVsCodeSettingReference))]
[JsonSerializable(typeof(GitLabVsCodeSettingReference[]))]
// Duo, Code Suggestions, GLQL and MCP. Most of those operations declare no response schema at all in
// GitLab's OpenAPI document, so their answers are surfaced as a raw JsonElement rather than as an
// invented DTO - which is what this root registration is for.
[JsonSerializable(typeof(JsonElement))]
[JsonSerializable(typeof(GenerateCodeCompletionRequest))]
[JsonSerializable(typeof(CodeSuggestionCurrentFile))]
[JsonSerializable(typeof(CodeSuggestionContextPart))]
[JsonSerializable(typeof(CodeSuggestionsDirectAccessRequest))]
[JsonSerializable(typeof(CodeSuggestionsEnabledRequest))]
[JsonSerializable(typeof(GenerateGitCommandRequest))]
[JsonSerializable(typeof(DuoChatRequest))]
[JsonSerializable(typeof(DuoChatCurrentFile))]
[JsonSerializable(typeof(DuoChatAdditionalContext))]
[JsonSerializable(typeof(EvaluateCodeReviewRequest))]
[JsonSerializable(typeof(ExecuteGlqlQueryRequest))]
[JsonSerializable(typeof(GitLabGlqlResult))]
[JsonSerializable(typeof(GitLabGlqlData))]
[JsonSerializable(typeof(GitLabGlqlPageInfo))]
[JsonSerializable(typeof(GitLabGlqlField))]
[JsonSerializable(typeof(McpJsonRpcRequest))]
[JsonSerializable(typeof(RenderMarkdownRequest))]
[JsonSerializable(typeof(GitLabRenderedMarkdown))]
[JsonSerializable(typeof(GitLabFeatureFlag))]
[JsonSerializable(typeof(GitLabFeatureFlag[]))]
[JsonSerializable(typeof(GitLabFeatureFlagStrategy))]
[JsonSerializable(typeof(GitLabFeatureFlagScope))]
[JsonSerializable(typeof(GitLabFeatureFlagBasicUserList))]
[JsonSerializable(typeof(GitLabFeatureFlagUserList))]
[JsonSerializable(typeof(GitLabFeatureFlagUserList[]))]
[JsonSerializable(typeof(GitLabFeatureFlagSettings))]
[JsonSerializable(typeof(CreateFeatureFlagRequest))]
[JsonSerializable(typeof(UpdateFeatureFlagRequest))]
[JsonSerializable(typeof(FeatureFlagStrategyRequest))]
[JsonSerializable(typeof(FeatureFlagStrategyScopeRequest))]
[JsonSerializable(typeof(UpdateFeatureFlagSettingsRequest))]
[JsonSerializable(typeof(CreateFeatureFlagUserListRequest))]
[JsonSerializable(typeof(UpdateFeatureFlagUserListRequest))]
[JsonSerializable(typeof(GitLabFeature))]
[JsonSerializable(typeof(GitLabFeature[]))]
[JsonSerializable(typeof(GitLabFeatureGate))]
[JsonSerializable(typeof(GitLabFeatureDefinition))]
[JsonSerializable(typeof(GitLabFeatureDefinition[]))]
[JsonSerializable(typeof(SetFeatureRequest))]
[JsonSerializable(typeof(UnleashClientRegistrationRequest))]
// The two Unleash GETs declare no response schema in the spec: the body is Unleash's own
// client-features document, versioned by Unleash rather than by GitLab. It is read back as a raw
// JsonElement, which needs its own registration because it is the ROOT type of those responses -
// the JsonElement members on other DTOs are covered by their owning type's metadata. Spelled out in
// full rather than adding a using: this file is merge=union across worktrees, and two branches both
// appending the same using directive would collide as CS0105.
[JsonSerializable(typeof(GitLabDuoWorkflowFlowCallbackHook))]
[JsonSerializable(typeof(GitLabDuoWorkflowFlowCallbackHook[]))]
[JsonSerializable(typeof(RegisterDuoWorkflowFlowCallbackRequest))]
[JsonSerializable(typeof(CreateDuoWorkflowRequest))]
[JsonSerializable(typeof(CreateDuoAgentWorkflowRequest))]
[JsonSerializable(typeof(DuoWorkflowAdditionalContext))]
[JsonSerializable(typeof(UpdateDuoWorkflowStatusRequest))]
[JsonSerializable(typeof(IngestDuoWorkflowAuditEventsRequest))]
[JsonSerializable(typeof(DuoWorkflowAuditEvent))]
[JsonSerializable(typeof(SubmitDuoWorkflowRiskClassificationRequest))]
[JsonSerializable(typeof(DuoWorkflowRiskClassificationClaim))]
[JsonSerializable(typeof(AddDuoCodeReviewCommentsRequest))]
[JsonSerializable(typeof(RevokeDuoWorkflowTokenRequest))]
[JsonSerializable(typeof(CreateDuoWorkflowCheckpointRequest))]
[JsonSerializable(typeof(DuoWorkflowChannelBlob))]
[JsonSerializable(typeof(CreateDuoWorkflowCheckpointWritesRequest))]
[JsonSerializable(typeof(DuoWorkflowCheckpointWrite))]
[JsonSerializable(typeof(CreateDuoWorkflowEventRequest))]
[JsonSerializable(typeof(UpdateDuoWorkflowEventRequest))]
[JsonSerializable(typeof(DuoWorkflowDirectAccessRequest))]
[JsonSerializable(typeof(ResumeDuoWorkflowRequest))]
// Every operation under /ai/duo_workflows except the flow callback hooks declares no response
// schema in the spec, so those bodies are surfaced as a raw JsonElement rather than as invented
// DTOs. Fully qualified because this file's using block is shared, append-only ground.
[JsonSerializable(typeof(GitLabMlflowKeyValue))]
[JsonSerializable(typeof(GitLabMlflowMetric))]
[JsonSerializable(typeof(GitLabMlflowExperiment))]
[JsonSerializable(typeof(GitLabMlflowExperimentResponse))]
[JsonSerializable(typeof(GitLabMlflowExperimentList))]
[JsonSerializable(typeof(GitLabMlflowNewExperiment))]
[JsonSerializable(typeof(GitLabMlflowRunInfo))]
[JsonSerializable(typeof(GitLabMlflowRunData))]
[JsonSerializable(typeof(GitLabMlflowRun))]
[JsonSerializable(typeof(GitLabMlflowUpdateRunResponse))]
[JsonSerializable(typeof(GitLabMlflowMetricHistory))]
[JsonSerializable(typeof(GitLabMlflowModelVersion))]
[JsonSerializable(typeof(GitLabMlflowArtifactUri))]
[JsonSerializable(typeof(MlflowMetricEntry))]
[JsonSerializable(typeof(MlflowParameterEntry))]
[JsonSerializable(typeof(CreateMlflowExperimentRequest))]
[JsonSerializable(typeof(DeleteMlflowExperimentRequest))]
[JsonSerializable(typeof(SearchMlflowExperimentsRequest))]
[JsonSerializable(typeof(SetMlflowExperimentTagRequest))]
[JsonSerializable(typeof(CreateMlflowRunRequest))]
[JsonSerializable(typeof(SearchMlflowRunsRequest))]
[JsonSerializable(typeof(UpdateMlflowRunRequest))]
[JsonSerializable(typeof(DeleteMlflowRunRequest))]
[JsonSerializable(typeof(LogMlflowMetricRequest))]
[JsonSerializable(typeof(LogMlflowParameterRequest))]
[JsonSerializable(typeof(SetMlflowRunTagRequest))]
[JsonSerializable(typeof(LogMlflowBatchRequest))]
[JsonSerializable(typeof(CreateMlflowModelVersionRequest))]
[JsonSerializable(typeof(UpdateMlflowModelVersionRequest))]
[JsonSerializable(typeof(GitLabGroupRelationsExportStatus))]
[JsonSerializable(typeof(GitLabGroupRelationsExportStatus[]))]
[JsonSerializable(typeof(GitLabGroupRelationsExportBatch))]
[JsonSerializable(typeof(ScheduleGroupRelationsExportRequest))]
[JsonSerializable(typeof(GitLabBulkImport))]
[JsonSerializable(typeof(GitLabBulkImport[]))]
[JsonSerializable(typeof(GitLabBulkImportEntity))]
[JsonSerializable(typeof(GitLabBulkImportEntity[]))]
[JsonSerializable(typeof(GitLabBulkImportEntityFailure))]
[JsonSerializable(typeof(GitLabBulkImportEntityFailure[]))]
[JsonSerializable(typeof(CreateBulkImportRequest))]
[JsonSerializable(typeof(BulkImportConfiguration))]
[JsonSerializable(typeof(BulkImportEntityRequest))]
[JsonSerializable(typeof(ImportGitHubGistsRequest))]
[JsonSerializable(typeof(GitLabOfflineExport))]
[JsonSerializable(typeof(GitLabOfflineExport[]))]
[JsonSerializable(typeof(CreateOfflineExportRequest))]
[JsonSerializable(typeof(CreateOfflineImportRequest))]
[JsonSerializable(typeof(OfflineExportEntityRequest))]
[JsonSerializable(typeof(OfflineImportEntityRequest))]
[JsonSerializable(typeof(OfflineTransferAwsS3Configuration))]
[JsonSerializable(typeof(OfflineTransferS3CompatibleConfiguration))]
[JsonSerializable(typeof(OfflineTransferGcsConfiguration))]
[JsonSerializable(typeof(OfflineTransferGcsHmacConfiguration))]
[JsonSerializable(typeof(OfflineTransferGcsAdcConfiguration))]
// Project import/export and project templates.
[JsonSerializable(typeof(GitLabProjectExportStatus))]
[JsonSerializable(typeof(GitLabProjectExportLinks))]
[JsonSerializable(typeof(GitLabProjectImportStatus))]
[JsonSerializable(typeof(GitLabProjectImportFailedRelation))]
[JsonSerializable(typeof(GitLabProjectRelationExportStatus))]
[JsonSerializable(typeof(GitLabProjectRelationExportStatus[]))]
[JsonSerializable(typeof(GitLabProjectRelationExportBatch))]
[JsonSerializable(typeof(GitLabProjectRelationImport))]
[JsonSerializable(typeof(GitLabImportedProject))]
[JsonSerializable(typeof(GitLabRemoteImportedProject))]
[JsonSerializable(typeof(GitLabProjectTemplate))]
[JsonSerializable(typeof(GitLabProjectTemplate[]))]
[JsonSerializable(typeof(GitLabProjectTemplateDetail))]
[JsonSerializable(typeof(ExportProjectRequest))]
[JsonSerializable(typeof(GitLabProjectExportUpload))]
[JsonSerializable(typeof(ExportProjectRelationsRequest))]
[JsonSerializable(typeof(ImportProjectFromGitRequest))]
// The two multipart imports are projected onto form fields rather than serialized as JSON bodies;
// they are registered so the "every model has metadata" guard stays exemption-free.
[JsonSerializable(typeof(ImportProjectArchiveRequest))]
[JsonSerializable(typeof(ImportProjectRelationRequest))]
[JsonSerializable(typeof(ImportProjectFromRemoteArchiveRequest))]
[JsonSerializable(typeof(ImportProjectFromS3Request))]
[JsonSerializable(typeof(ImportProjectFromGitHubRequest))]
[JsonSerializable(typeof(ImportProjectFromBitbucketRequest))]
[JsonSerializable(typeof(ImportProjectFromBitbucketServerRequest))]
[JsonSerializable(typeof(CancelGitHubImportRequest))]
// Debian package registry: distributions are typed JSON; everything under packages/debian is raw
// bytes (GitLabFileResponse) and never reaches the serializer.
[JsonSerializable(typeof(GitLabDebianDistribution))]
[JsonSerializable(typeof(GitLabDebianDistribution[]))]
[JsonSerializable(typeof(CreateDebianDistributionRequest))]
[JsonSerializable(typeof(UpdateDebianDistributionRequest))]
[JsonSerializable(typeof(AuthorizeDebianPackageUploadRequest))]
// Package registries: Cargo, RPM and the RubyGems query options need no JSON metadata (Cargo and RPM
// have no JSON request/response bodies at all; RubyGemsDependencyListOptions is [GitLabQuery] and is
// projected onto a query string). Composer's create request and PyPI's upload metadata are projected
// onto a JSON body / multipart form fields respectively, but are registered all the same so the
// library's "every model is registered" guard stays a real check rather than one with exemptions.
[JsonSerializable(typeof(ComposerPackageCreateRequest))]
[JsonSerializable(typeof(PyPiPackageUploadRequest))]
// Active context (instance-administrator-only ActiveContext admin API).
[JsonSerializable(typeof(GitLabActiveContextConnection))]
[JsonSerializable(typeof(GitLabActiveContextConnection[]))]
[JsonSerializable(typeof(GitLabActiveContextCollectionDetail))]
[JsonSerializable(typeof(GitLabActiveContextCodeEnabledNamespace))]
[JsonSerializable(typeof(UpdateActiveContextEnabledNamespaceStateRequest))]
[JsonSerializable(typeof(UpdateActiveContextCollectionRequest))]
[JsonSerializable(typeof(ActivateActiveContextConnectionRequest))]
[JsonSerializable(typeof(DeactivateActiveContextConnectionRequest))]
[JsonSerializable(typeof(ReplayActiveContextDeadQueueRequest))]
// Code search (instance-administrator-only Zoekt admin API).
[JsonSerializable(typeof(GitLabZoektIndexedNamespace))]
[JsonSerializable(typeof(GitLabZoektIndexedNamespace[]))]
[JsonSerializable(typeof(GitLabZoektNode))]
[JsonSerializable(typeof(GitLabZoektNode[]))]
[JsonSerializable(typeof(GitLabZoektProjectIndexResult))]
[JsonSerializable(typeof(UpdateZoektNamespaceReplicasRequest))]
[JsonSerializable(typeof(AddZoektIndexedNamespaceRequest))]
// Knowledge graph (instance-administrator-only Knowledge Graph admin API).
[JsonSerializable(typeof(GitLabKnowledgeGraphNamespace))]
[JsonSerializable(typeof(GitLabKnowledgeGraphNamespace[]))]
// Analytics: group activity counts, project deployment frequency and code review analytics. DORA
// metrics (/groups/:id/dora/metrics, /projects/:id/dora/metrics) declare no response schema in
// GitLab's OpenAPI document, so those answers reuse the root JsonElement registration above rather
// than a second one here.
[JsonSerializable(typeof(GitLabGroupIssuesCount))]
[JsonSerializable(typeof(GitLabGroupMergeRequestsCount))]
[JsonSerializable(typeof(GitLabGroupNewMembersCount))]
[JsonSerializable(typeof(GitLabDeploymentFrequency))]
[JsonSerializable(typeof(GitLabDeploymentFrequency[]))]
[JsonSerializable(typeof(GitLabCodeReviewAnalyticsItem))]
[JsonSerializable(typeof(GitLabCodeReviewAnalyticsItem[]))]
// Usage data / Service Ping (/usage_data/*). Every GET here (non_sql_metrics, queries, service_ping,
// metric_definitions) declares no response schema in GitLab's OpenAPI document - usage-ping payloads
// are famously large and semi-structured - so those answers reuse the root JsonElement registration
// above rather than invented DTOs.
[JsonSerializable(typeof(UsageDataEventRequest))]
[JsonSerializable(typeof(TrackEventRequest))]
[JsonSerializable(typeof(TrackEventsRequest))]
// Audit events, compliance policy settings, and the group credentials inventory.
[JsonSerializable(typeof(GitLabAuditEvent))]
[JsonSerializable(typeof(GitLabAuditEvent[]))]
[JsonSerializable(typeof(GitLabCompliancePolicySettings))]
[JsonSerializable(typeof(UpdateCompliancePolicySettingsRequest))]
[JsonSerializable(typeof(SetComplianceExternalControlStatusRequest))]
[JsonSerializable(typeof(GitLabGroupManagedSshKey))]
[JsonSerializable(typeof(GitLabGroupManagedSshKey[]))]
// Broadcast messages.
[JsonSerializable(typeof(GitLabBroadcastMessage))]
[JsonSerializable(typeof(GitLabBroadcastMessage[]))]
[JsonSerializable(typeof(CreateBroadcastMessageRequest))]
[JsonSerializable(typeof(UpdateBroadcastMessageRequest))]
// Error tracking.
[JsonSerializable(typeof(GitLabErrorTrackingClientKey))]
[JsonSerializable(typeof(GitLabErrorTrackingClientKey[]))]
[JsonSerializable(typeof(GitLabErrorTrackingSettings))]
[JsonSerializable(typeof(CreateErrorTrackingSettingsRequest))]
[JsonSerializable(typeof(UpdateErrorTrackingSettingsRequest))]
// Mobile push subscriptions.
[JsonSerializable(typeof(GitLabMobilePushSubscription))]
[JsonSerializable(typeof(RegisterMobilePushSubscriptionRequest))]
// Search: admin search migrations and project semantic code search.
[JsonSerializable(typeof(GitLabSearchMigration))]
[JsonSerializable(typeof(GitLabSemanticCodeSearchResult))]
[JsonSerializable(typeof(GitLabSemanticCodeSearchMatch))]
[JsonSerializable(typeof(GitLabSemanticCodeSearchMatch[]))]
[JsonSerializable(typeof(GitLabSemanticCodeSnippetRange))]
// Rollouts: the CD orchestrator (AutoFlow) event webhook.
[JsonSerializable(typeof(GitLabCdRollout))]
[JsonSerializable(typeof(IngestRolloutEventRequest))]
[JsonSerializable(typeof(RolloutEventPayload))]
[JsonSerializable(typeof(RolloutChannelToken))]
// CI catalog: publishing a component project release as a version.
[JsonSerializable(typeof(CiCatalogPublishRequest))]
[JsonSerializable(typeof(GitLabCiCatalogPublishResult))]
// Notification settings.
[JsonSerializable(typeof(GitLabNotificationSettings))]
[JsonSerializable(typeof(UpdateNotificationSettingsRequest))]
// System hooks: single URL-variable / custom-header update, added alongside the existing hook DTOs.
[JsonSerializable(typeof(UpdateSystemHookUrlVariableRequest))]
[JsonSerializable(typeof(UpdateSystemHookCustomHeaderRequest))]
[JsonSerializable(typeof(UpdateEnterpriseUserRequest))]
[JsonSerializable(typeof(GitLabExperiment))]
[JsonSerializable(typeof(GitLabExperiment[]))]
[JsonSerializable(typeof(GitLabExperimentCurrentStatus))]
[JsonSerializable(typeof(GitLabExperimentAssignment))]
[JsonSerializable(typeof(ForceExperimentAssignmentRequest))]
[JsonSerializable(typeof(TokenExchangeRequest))]
[JsonSerializable(typeof(GitLabTokenExchangeResult))]
// long-tail-cleanup: secure file upload, wiki attachment upload, and the group-label collection-route
// delete - the multipart/query-form leftovers a prior wave skipped before the transport supported them.
[JsonSerializable(typeof(GitLabWikiAttachment))]
[JsonSerializable(typeof(GitLabWikiAttachmentLink))]
// Conan package registry (v1 instance-wide, v1 and v2 project-scoped). JsonElement itself is already
// registered above (see the Duo/GLQL note) - the entries below are only the named wrapper DTOs.
[JsonSerializable(typeof(GitLabConanRecipeSnapshot))]
[JsonSerializable(typeof(GitLabConanRecipeUrls))]
[JsonSerializable(typeof(GitLabConanPackageSnapshot))]
[JsonSerializable(typeof(GitLabConanPackageUrls))]
[JsonSerializable(typeof(GitLabConanUploadUrls))]
[JsonSerializable(typeof(GitLabConanRevisionInfo))]
[JsonSerializable(typeof(GitLabConanRecipeRevisions))]
[JsonSerializable(typeof(GitLabConanPackageRevisions))]
[JsonSerializable(typeof(GitLabConanFileList))]
// Packages: Generic (Maven/Go proxies, the generic package format, and format-agnostic package/file/
// pipeline management). PackagePipeline reuses GitLabPipeline/GitLabPipeline[], already registered above.
[JsonSerializable(typeof(GitLabPackageFile))]
[JsonSerializable(typeof(GitLabPackageFile[]))]
[JsonSerializable(typeof(AuthorizeGenericPackageFileUploadRequest))]
[JsonSerializable(typeof(GitLabGoModuleVersionInfo))]
// Packages: NuGet. The V2 OData feed and symbol-file endpoints declare no JSON schema and are surfaced as
// GitLabFileResponse, so only the V3 protocol's typed responses need metadata here.
[JsonSerializable(typeof(GitLabNugetServiceIndex))]
[JsonSerializable(typeof(GitLabNugetPackagesMetadata))]
[JsonSerializable(typeof(GitLabNugetPackagesMetadataItem))]
[JsonSerializable(typeof(GitLabNugetPackageMetadata))]
[JsonSerializable(typeof(GitLabNugetPackageMetadataCatalogEntry))]
[JsonSerializable(typeof(GitLabNugetDependencyGroup))]
[JsonSerializable(typeof(GitLabNugetDependency))]
[JsonSerializable(typeof(GitLabNugetSearchResults))]
[JsonSerializable(typeof(GitLabNugetSearchResult))]
[JsonSerializable(typeof(GitLabNugetSearchResultVersion))]
[JsonSerializable(typeof(GitLabNugetPackagesVersions))]
// The npm registry protocol. PublishForProjectAsync's response has no schema in the spec (declared as
// a bare 200 "OK"), so it is read back as the JsonElement already registered above rather than a
// second, duplicate [JsonSerializable(typeof(JsonElement))] attribute.
[JsonSerializable(typeof(GitLabNpmPackage))]
[JsonSerializable(typeof(GitLabNpmDistTags))]
// Batched background migrations/operations, Data management, Database dictionary, Sidekiq admin and
// Migrations - all instance-administrator-only. SidekiqQueueJobDeleteOptions and every *ListOptions /
// *GetOptions type here are [GitLabQuery] query-string models and are deliberately NOT registered.
[JsonSerializable(typeof(GitLabBatchedBackgroundMigration))]
[JsonSerializable(typeof(GitLabBatchedBackgroundMigration[]))]
[JsonSerializable(typeof(GitLabBatchedBackgroundOperation))]
[JsonSerializable(typeof(GitLabBatchedBackgroundOperation[]))]
[JsonSerializable(typeof(BackgroundJobDatabaseRequest))]
[JsonSerializable(typeof(GitLabAdminModelChecksumInfo))]
[JsonSerializable(typeof(GitLabAdminModelRecord))]
[JsonSerializable(typeof(GitLabAdminModelRecord[]))]
[JsonSerializable(typeof(RecalculateModelChecksumsRequest))]
[JsonSerializable(typeof(GitLabDictionaryTable))]
[JsonSerializable(typeof(GitLabDictionaryTable[]))]
// Applications (instance-wide /applications and per-user /user/applications OAuth app registration).
[JsonSerializable(typeof(GitLabApplication))]
[JsonSerializable(typeof(GitLabApplication[]))]
[JsonSerializable(typeof(GitLabApplicationWithSecret))]
[JsonSerializable(typeof(CreateApplicationRequest))]
[JsonSerializable(typeof(UpdateApplicationRequest))]
// Instance (appearance, application settings, statistics, metadata, plan limits).
[JsonSerializable(typeof(GitLabAppearance))]
[JsonSerializable(typeof(GitLabApplicationSettings))]
[JsonSerializable(typeof(UpdateApplicationSettingsRequest))]
[JsonSerializable(typeof(GitLabBranchProtectionDefaults))]
[JsonSerializable(typeof(GitLabBranchProtectionAccessRequirement))]
[JsonSerializable(typeof(GitLabDependencyManagementSettings))]
[JsonSerializable(typeof(GitLabApplicationStatistics))]
[JsonSerializable(typeof(GitLabMetadata))]
[JsonSerializable(typeof(GitLabKasMetadata))]
[JsonSerializable(typeof(GitLabPlanLimits))]
[JsonSerializable(typeof(GitLabPlanLimitHistoryEntry))]
[JsonSerializable(typeof(UpdatePlanLimitsRequest))]
// Namespaces, Namespace projects, Organizations and the Groups audit-event/placeholder-reassignment/
// security-settings additions.
[JsonSerializable(typeof(GitLabNamespace[]))]
[JsonSerializable(typeof(GitLabNamespaceExistence))]
[JsonSerializable(typeof(GitLabNamespaceSubscription))]
[JsonSerializable(typeof(GitLabNamespaceSubscriptionPlan))]
[JsonSerializable(typeof(GitLabNamespaceSubscriptionUsage))]
[JsonSerializable(typeof(GitLabNamespaceSubscriptionBilling))]
[JsonSerializable(typeof(GitLabNamespaceStorageLimitExclusion))]
[JsonSerializable(typeof(GitLabNamespaceStorageLimitExclusion[]))]
[JsonSerializable(typeof(CreateNamespaceStorageLimitExclusionRequest))]
[JsonSerializable(typeof(GitLabNamespaceProject))]
[JsonSerializable(typeof(GitLabNamespaceProject[]))]
[JsonSerializable(typeof(GitLabNamespaceProjectLicense))]
[JsonSerializable(typeof(GitLabOrganization))]
[JsonSerializable(typeof(CreateOrganizationRequest))]
[JsonSerializable(typeof(GitLabGroupAuditEvent))]
[JsonSerializable(typeof(UpdateGroupSecuritySettingsRequest))]
internal sealed partial class GitLabJsonContext : JsonSerializerContext;